begin_unit|revision:1.0.0;language:C;cregit-version:0.0.1
begin_comment
comment|/*  * Copyright (C) Igor Sysoev  */
end_comment

begin_ifndef
ifndef|#
directive|ifndef
name|_NGX_HTTP_SSI_FILTER_H_INCLUDED_
end_ifndef

begin_define
DECL|macro|_NGX_HTTP_SSI_FILTER_H_INCLUDED_
define|#
directive|define
name|_NGX_HTTP_SSI_FILTER_H_INCLUDED_
end_define

begin_include
include|#
directive|include
file|<ngx_config.h>
end_include

begin_include
include|#
directive|include
file|<ngx_core.h>
end_include

begin_include
include|#
directive|include
file|<ngx_http.h>
end_include

begin_define
DECL|macro|NGX_HTTP_SSI_MAX_PARAMS
define|#
directive|define
name|NGX_HTTP_SSI_MAX_PARAMS
value|16
end_define

begin_define
DECL|macro|NGX_HTTP_SSI_COMMAND_LEN
define|#
directive|define
name|NGX_HTTP_SSI_COMMAND_LEN
value|32
end_define

begin_define
DECL|macro|NGX_HTTP_SSI_PARAM_LEN
define|#
directive|define
name|NGX_HTTP_SSI_PARAM_LEN
value|32
end_define

begin_define
DECL|macro|NGX_HTTP_SSI_PARAMS_N
define|#
directive|define
name|NGX_HTTP_SSI_PARAMS_N
value|4
end_define

begin_typedef
DECL|struct|__anon29b3960f0108
typedef|typedef
struct|struct
block|{
DECL|member|hash
name|ngx_hash_t
name|hash
decl_stmt|;
DECL|member|commands
name|ngx_hash_keys_arrays_t
name|commands
decl_stmt|;
DECL|typedef|ngx_http_ssi_main_conf_t
block|}
name|ngx_http_ssi_main_conf_t
typedef|;
end_typedef

begin_typedef
DECL|struct|__anon29b3960f0208
typedef|typedef
struct|struct
block|{
DECL|member|buf
name|ngx_buf_t
modifier|*
name|buf
decl_stmt|;
DECL|member|pos
name|u_char
modifier|*
name|pos
decl_stmt|;
DECL|member|copy_start
name|u_char
modifier|*
name|copy_start
decl_stmt|;
DECL|member|copy_end
name|u_char
modifier|*
name|copy_end
decl_stmt|;
DECL|member|key
name|ngx_uint_t
name|key
decl_stmt|;
DECL|member|command
name|ngx_str_t
name|command
decl_stmt|;
DECL|member|params
name|ngx_array_t
name|params
decl_stmt|;
DECL|member|param
name|ngx_table_elt_t
modifier|*
name|param
decl_stmt|;
DECL|member|params_array
name|ngx_table_elt_t
name|params_array
index|[
name|NGX_HTTP_SSI_PARAMS_N
index|]
decl_stmt|;
DECL|member|in
name|ngx_chain_t
modifier|*
name|in
decl_stmt|;
DECL|member|out
name|ngx_chain_t
modifier|*
name|out
decl_stmt|;
DECL|member|last_out
name|ngx_chain_t
modifier|*
modifier|*
name|last_out
decl_stmt|;
DECL|member|busy
name|ngx_chain_t
modifier|*
name|busy
decl_stmt|;
DECL|member|free
name|ngx_chain_t
modifier|*
name|free
decl_stmt|;
DECL|member|state
name|ngx_uint_t
name|state
decl_stmt|;
DECL|member|saved_state
name|ngx_uint_t
name|saved_state
decl_stmt|;
DECL|member|saved
name|size_t
name|saved
decl_stmt|;
DECL|member|looked
name|size_t
name|looked
decl_stmt|;
DECL|member|value_len
name|size_t
name|value_len
decl_stmt|;
DECL|member|variables
name|ngx_array_t
name|variables
decl_stmt|;
DECL|member|output
name|ngx_uint_t
name|output
decl_stmt|;
comment|/* unsigned  output:1; */
DECL|member|value_buf
name|void
modifier|*
name|value_buf
decl_stmt|;
DECL|member|timefmt
name|ngx_str_t
name|timefmt
decl_stmt|;
DECL|member|errmsg
name|ngx_str_t
name|errmsg
decl_stmt|;
DECL|typedef|ngx_http_ssi_ctx_t
block|}
name|ngx_http_ssi_ctx_t
typedef|;
end_typedef

begin_typedef
DECL|typedef|ngx_http_ssi_command_pt
typedef|typedef
name|ngx_int_t
function_decl|(
modifier|*
name|ngx_http_ssi_command_pt
function_decl|)
parameter_list|(
name|ngx_http_request_t
modifier|*
name|r
parameter_list|,
name|ngx_http_ssi_ctx_t
modifier|*
name|ctx
parameter_list|,
name|ngx_str_t
modifier|*
modifier|*
parameter_list|)
function_decl|;
end_typedef

begin_typedef
DECL|struct|__anon29b3960f0308
typedef|typedef
struct|struct
block|{
DECL|member|name
name|ngx_str_t
name|name
decl_stmt|;
DECL|member|index
name|ngx_uint_t
name|index
decl_stmt|;
DECL|member|mandatory
name|unsigned
name|mandatory
range|:
literal|1
decl_stmt|;
DECL|member|multiple
name|unsigned
name|multiple
range|:
literal|1
decl_stmt|;
DECL|typedef|ngx_http_ssi_param_t
block|}
name|ngx_http_ssi_param_t
typedef|;
end_typedef

begin_typedef
DECL|struct|__anon29b3960f0408
typedef|typedef
struct|struct
block|{
DECL|member|name
name|ngx_str_t
name|name
decl_stmt|;
DECL|member|handler
name|ngx_http_ssi_command_pt
name|handler
decl_stmt|;
DECL|member|params
name|ngx_http_ssi_param_t
modifier|*
name|params
decl_stmt|;
DECL|member|conditional
name|unsigned
name|conditional
range|:
literal|1
decl_stmt|;
DECL|member|flush
name|unsigned
name|flush
range|:
literal|1
decl_stmt|;
DECL|typedef|ngx_http_ssi_command_t
block|}
name|ngx_http_ssi_command_t
typedef|;
end_typedef

begin_decl_stmt
specifier|extern
name|ngx_module_t
name|ngx_http_ssi_filter_module
decl_stmt|;
end_decl_stmt

begin_endif
endif|#
directive|endif
end_endif

begin_comment
comment|/* _NGX_HTTP_SSI_FILTER_H_INCLUDED_ */
end_comment

end_unit

