begin_unit|revision:1.0.0;language:C;cregit-version:0.0.1
begin_comment
comment|/*  * small file in malloc()ed memory, mmap()ed file, file descriptor only,  * file access time only (to estimate could pages still be in memory),  * translated URI (ngx_http_index_hanlder),  * compiled script (ngx_http_ssi_filter).  */
end_comment

begin_define
DECL|macro|NGX_HTTP_CACHE_ENTRY_DELETED
define|#
directive|define
name|NGX_HTTP_CACHE_ENTRY_DELETED
value|0x00000001
end_define

begin_define
DECL|macro|NGX_HTTP_CACHE_ENTRY_MMAPED
define|#
directive|define
name|NGX_HTTP_CACHE_ENTRY_MMAPED
value|0x00000002
end_define

begin_comment
comment|/* "/" -> "/index.html" in ngx_http_index_handler */
end_comment

begin_define
DECL|macro|NGX_HTTP_CACHE_ENTRY_URI
define|#
directive|define
name|NGX_HTTP_CACHE_ENTRY_URI
value|0x00000004
end_define

begin_comment
comment|/* 301 location "/dir" -> "dir/" in ngx_http_core_handler */
end_comment

begin_comment
comment|/* compiled script in ngx_http_ssi_filter  */
end_comment

begin_define
DECL|macro|NGX_HTTP_CACHE_ENTRY_SCRIPT
define|#
directive|define
name|NGX_HTTP_CACHE_ENTRY_SCRIPT
value|0x00000008
end_define

begin_define
DECL|macro|NGX_HTTP_CACHE_FILTER_FLAGS
define|#
directive|define
name|NGX_HTTP_CACHE_FILTER_FLAGS
value|0xFFFF0000
end_define

begin_typedef
DECL|struct|__anon296840ed0408
typedef|typedef
struct|struct
block|{
DECL|member|fd
name|ngx_fd_t
name|fd
decl_stmt|;
DECL|member|size
name|off_t
name|size
decl_stmt|;
DECL|member|data
name|void
modifier|*
name|data
decl_stmt|;
DECL|member|accessed
name|time_t
name|accessed
decl_stmt|;
DECL|member|last_modified
name|time_t
name|last_modified
decl_stmt|;
DECL|member|updated
name|time_t
name|updated
decl_stmt|;
comment|/* no needed with kqueue */
DECL|member|refs
name|int
name|refs
decl_stmt|;
DECL|member|flags
name|int
name|flags
decl_stmt|;
DECL|typedef|ngx_http_cache_entry_t
block|}
name|ngx_http_cache_entry_t
typedef|;
end_typedef

begin_typedef
DECL|struct|__anon296840ed0508
typedef|typedef
struct|struct
block|{
DECL|member|crc
name|u_int32_t
name|crc
decl_stmt|;
DECL|member|uri
name|ngx_str_t
name|uri
decl_stmt|;
DECL|member|cache
name|ngx_http_cache_t
modifier|*
name|cache
decl_stmt|;
DECL|typedef|ngx_http_cache_hash_entry_t
block|}
name|ngx_http_cache_hash_entry_t
typedef|;
end_typedef

begin_typedef
DECL|struct|__anon296840ed0608
typedef|typedef
struct|struct
block|{
DECL|member|cache
name|ngx_http_cache_t
modifier|*
name|cache
decl_stmt|;
DECL|member|crc
name|u_int32_t
name|crc
decl_stmt|;
DECL|member|n
name|int
name|n
decl_stmt|;
DECL|typedef|ngx_http_cache_handle_t
block|}
name|ngx_http_cache_handle_t
typedef|;
end_typedef

begin_function
DECL|function|ngx_http_cache_get (ngx_http_cache_hash_t * cache_hash,ngx_str_t * uri,ngx_http_cache_handle_t * h)
name|int
name|ngx_http_cache_get
parameter_list|(
name|ngx_http_cache_hash_t
modifier|*
name|cache_hash
parameter_list|,
name|ngx_str_t
modifier|*
name|uri
parameter_list|,
name|ngx_http_cache_handle_t
modifier|*
name|h
parameter_list|)
block|{
name|int
name|hi
decl_stmt|;
name|ngx_http_cache_hash_entry_t
modifier|*
name|entry
decl_stmt|;
name|h
operator|->
name|crc
operator|=
name|ngx_crc
argument_list|(
name|uri
operator|->
name|data
argument_list|,
name|uri
operator|->
name|len
argument_list|)
expr_stmt|;
name|hi
operator|=
name|h
operator|->
name|crc
operator|%
name|cache_hash
operator|->
name|size
expr_stmt|;
name|entry
operator|=
name|cache_hash
index|[
name|hi
index|]
operator|.
name|elts
expr_stmt|;
for|for
control|(
name|i
operator|=
literal|0
init|;
name|i
operator|<
name|cache_hash
index|[
name|hi
index|]
operator|.
name|nelts
condition|;
name|i
operator|++
control|)
block|{
if|if
condition|(
name|entry
index|[
name|i
index|]
operator|.
name|crc
operator|==
name|crc
operator|&&
name|entry
index|[
name|i
index|]
operator|.
name|uri
operator|.
name|len
operator|==
name|uri
operator|->
name|len
operator|&&
name|ngx_strncmp
argument_list|(
name|entry
index|[
name|i
index|]
operator|.
name|uri
operator|.
name|data
argument_list|,
name|uri
operator|->
name|data
argument_list|,
name|uri
operator|->
name|len
argument_list|)
operator|==
literal|0
block|{
name|h
operator|->
name|cache
operator|=
name|entry
index|[
name|i
index|]
operator|.
name|cache
expr_stmt|;
name|h
operator|->
name|cache
operator|->
name|refs
operator|++
expr_stmt|;
name|h
operator|->
name|n
operator|=
name|hi
expr_stmt|;
return|return
name|NGX_OK
return|;
block|}
block|}
return|return
name|NGX_ERROR
return|;
block|}
end_function

begin_comment
comment|/* 32-bit crc16 */
end_comment

begin_function
name|int
name|ngx_crc
parameter_list|(
name|char
modifier|*
name|data
parameter_list|,
name|size_t
name|len
parameter_list|)
block|{
name|u_int32_t
name|sum
decl_stmt|;
for|for
control|(
name|sum
operator|=
literal|0
init|;
name|len
condition|;
name|len
operator|--
control|)
block|{
comment|/*          * gcc 2.95.2 x86 and icc 7.1.006 compile that operator          * into the single rol opcode.          * msvc 6.0sp2 compiles it into four opcodes.          */
name|sum
operator|=
name|sum
operator|>>
literal|1
operator||
name|sum
operator|<<
literal|31
expr_stmt|;
name|sum
operator|+=
operator|*
name|data
operator|++
expr_stmt|;
block|}
return|return
name|sum
return|;
block|}
end_function

end_unit

