begin_unit|revision:1.0.0;language:C;cregit-version:0.0.1
begin_comment
comment|/*    TODO: Win32 inet_ntoa          ngx_inet_ntop */
end_comment

begin_include
include|#
directive|include
file|<ngx_config.h>
end_include

begin_include
include|#
directive|include
file|<ngx_core.h>
end_include

begin_include
include|#
directive|include
file|<ngx_string.h>
end_include

begin_include
include|#
directive|include
file|<ngx_files.h>
end_include

begin_include
include|#
directive|include
file|<ngx_log.h>
end_include

begin_include
include|#
directive|include
file|<ngx_alloc.h>
end_include

begin_include
include|#
directive|include
file|<ngx_hunk.h>
end_include

begin_include
include|#
directive|include
file|<ngx_connection.h>
end_include

begin_include
include|#
directive|include
file|<ngx_http.h>
end_include

begin_include
include|#
directive|include
file|<ngx_http_config.h>
end_include

begin_include
include|#
directive|include
file|<ngx_http_core.h>
end_include

begin_comment
comment|/* STUB */
end_comment

begin_include
include|#
directive|include
file|<ngx_http_output_filter.h>
end_include

begin_function_decl
name|int
name|ngx_http_static_handler
parameter_list|(
name|ngx_http_request_t
modifier|*
name|r
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|int
name|ngx_http_index_handler
parameter_list|(
name|ngx_http_request_t
modifier|*
name|r
parameter_list|)
function_decl|;
end_function_decl

begin_comment
comment|/* */
end_comment

begin_function_decl
name|int
name|ngx_http_init_connection
parameter_list|(
name|ngx_connection_t
modifier|*
name|c
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|int
name|ngx_http_init_request
parameter_list|(
name|ngx_event_t
modifier|*
name|ev
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|int
name|ngx_http_process_request
parameter_list|(
name|ngx_event_t
modifier|*
name|ev
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|int
name|ngx_http_process_request_line
parameter_list|(
name|ngx_http_request_t
modifier|*
name|r
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|int
name|ngx_http_process_request_header
parameter_list|(
name|ngx_http_request_t
modifier|*
name|r
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|int
name|ngx_http_process_request_header_line
parameter_list|(
name|ngx_http_request_t
modifier|*
name|r
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|int
name|ngx_http_block_read
parameter_list|(
name|ngx_event_t
modifier|*
name|ev
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|int
name|ngx_http_read_discarded_body
parameter_list|(
name|ngx_event_t
modifier|*
name|ev
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|int
name|ngx_http_event_handler
parameter_list|(
name|ngx_http_request_t
modifier|*
name|r
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|int
name|ngx_http_handler
parameter_list|(
name|ngx_http_request_t
modifier|*
name|r
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|int
name|ngx_http_set_default_handler
parameter_list|(
name|ngx_http_request_t
modifier|*
name|r
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|int
name|ngx_http_writer
parameter_list|(
name|ngx_event_t
modifier|*
name|ev
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|int
name|ngx_http_set_lingering_close
parameter_list|(
name|ngx_http_request_t
modifier|*
name|r
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|int
name|ngx_http_keepalive_handler
parameter_list|(
name|ngx_event_t
modifier|*
name|ev
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|int
name|ngx_http_lingering_close
parameter_list|(
name|ngx_event_t
modifier|*
name|ev
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|int
name|ngx_http_special_response
parameter_list|(
name|ngx_http_request_t
modifier|*
name|r
parameter_list|,
name|int
name|error
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|int
name|ngx_http_redirect
parameter_list|(
name|ngx_http_request_t
modifier|*
name|r
parameter_list|,
name|int
name|redirect
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|int
name|ngx_http_error
parameter_list|(
name|ngx_http_request_t
modifier|*
name|r
parameter_list|,
name|int
name|error
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|int
name|ngx_http_close_request
parameter_list|(
name|ngx_http_request_t
modifier|*
name|r
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|size_t
name|ngx_http_log_error
parameter_list|(
name|void
modifier|*
name|data
parameter_list|,
name|char
modifier|*
name|buf
parameter_list|,
name|size_t
name|len
parameter_list|)
function_decl|;
end_function_decl

begin_decl_stmt
DECL|variable|header_errors
specifier|static
name|char
modifier|*
name|header_errors
index|[]
init|=
block|{
literal|"client %s sent invalid method"
block|,
literal|"client %s sent invalid request"
block|,
literal|"client %s sent too long URI"
block|,
literal|"client %s sent HEAD method in HTTP/0.9 request"
block|}
decl_stmt|;
end_decl_stmt

begin_function
DECL|function|ngx_http_init_connection (ngx_connection_t * c)
name|int
name|ngx_http_init_connection
parameter_list|(
name|ngx_connection_t
modifier|*
name|c
parameter_list|)
block|{
name|ngx_event_t
modifier|*
name|ev
decl_stmt|;
name|struct
name|sockaddr
modifier|*
name|addr
decl_stmt|;
name|ngx_http_server_t
modifier|*
name|srv
decl_stmt|;
name|ngx_http_log_ctx_t
modifier|*
name|ctx
decl_stmt|;
name|ev
operator|=
name|c
operator|->
name|read
expr_stmt|;
name|ev
operator|->
name|event_handler
operator|=
name|ngx_http_init_request
expr_stmt|;
name|srv
operator|=
operator|(
name|ngx_http_server_t
operator|*
operator|)
name|c
operator|->
name|server
expr_stmt|;
name|ngx_test_null
argument_list|(
name|c
operator|->
name|pool
argument_list|,
name|ngx_create_pool
argument_list|(
name|srv
operator|->
name|connection_pool_size
argument_list|,
name|ev
operator|->
name|log
argument_list|)
argument_list|,
name|NGX_ERROR
argument_list|)
expr_stmt|;
name|ngx_test_null
argument_list|(
name|addr
argument_list|,
name|ngx_palloc
argument_list|(
name|c
operator|->
name|pool
argument_list|,
name|c
operator|->
name|socklen
argument_list|)
argument_list|,
name|NGX_ERROR
argument_list|)
expr_stmt|;
name|ngx_memcpy
argument_list|(
name|addr
argument_list|,
name|c
operator|->
name|sockaddr
argument_list|,
name|c
operator|->
name|socklen
argument_list|)
expr_stmt|;
name|c
operator|->
name|sockaddr
operator|=
name|addr
expr_stmt|;
name|ngx_test_null
argument_list|(
name|c
operator|->
name|addr_text
argument_list|,
name|ngx_palloc
argument_list|(
name|c
operator|->
name|pool
argument_list|,
name|c
operator|->
name|addr_textlen
argument_list|)
argument_list|,
name|NGX_ERROR
argument_list|)
expr_stmt|;
if|#
directive|if
operator|(
name|WIN32
operator|)
name|c
operator|->
name|addr_text
operator|=
name|inet_ntoa
argument_list|(
operator|(
expr|struct
name|in_addr
operator|*
operator|)
operator|(
operator|(
name|char
operator|*
operator|)
name|c
operator|->
name|sockaddr
operator|+
name|c
operator|->
name|addr
operator|)
argument_list|)
expr_stmt|;
else|#
directive|else
name|inet_ntop
argument_list|(
name|c
operator|->
name|family
argument_list|,
operator|(
name|char
operator|*
operator|)
name|c
operator|->
name|sockaddr
operator|+
name|c
operator|->
name|addr
argument_list|,
name|c
operator|->
name|addr_text
argument_list|,
name|c
operator|->
name|addr_textlen
argument_list|)
expr_stmt|;
endif|#
directive|endif
name|ngx_test_null
argument_list|(
name|ctx
argument_list|,
name|ngx_pcalloc
argument_list|(
name|c
operator|->
name|pool
argument_list|,
sizeof|sizeof
argument_list|(
name|ngx_http_log_ctx_t
argument_list|)
argument_list|)
argument_list|,
name|NGX_ERROR
argument_list|)
expr_stmt|;
name|ctx
operator|->
name|client
operator|=
name|c
operator|->
name|addr_text
expr_stmt|;
name|ctx
operator|->
name|action
operator|=
literal|"reading client request line"
expr_stmt|;
name|c
operator|->
name|log
operator|->
name|data
operator|=
name|ctx
expr_stmt|;
name|c
operator|->
name|log
operator|->
name|handler
operator|=
name|ngx_http_log_error
expr_stmt|;
if|#
directive|if
operator|(
name|HAVE_DEFERRED_ACCEPT
operator|)
if|if
condition|(
name|ev
operator|->
name|ready
condition|)
block|{
return|return
name|ngx_http_init_request
argument_list|(
name|ev
argument_list|)
return|;
block|}
else|else
block|{
endif|#
directive|endif
name|ngx_add_timer
argument_list|(
name|ev
argument_list|,
name|c
operator|->
name|post_accept_timeout
argument_list|)
expr_stmt|;
if|#
directive|if
operator|(
name|USE_KQUEUE
operator|)
return|return
name|ngx_add_event
argument_list|(
name|ev
argument_list|,
name|NGX_READ_EVENT
argument_list|,
name|NGX_CLEAR_EVENT
argument_list|)
return|;
else|#
directive|else
if|#
directive|if
operator|(
name|HAVE_AIO_EVENT
operator|)
if|if
condition|(
name|ngx_event_type
operator|==
name|NGX_AIO_EVENT
condition|)
return|return
name|ngx_http_init_request
argument_list|(
name|ev
argument_list|)
return|;
if|else
endif|#
directive|endif
if|#
directive|if
operator|(
name|HAVE_CLEAR_EVENT
operator|)
if|if
condition|(
name|ngx_event_type
operator|==
name|NGX_KQUEUE_EVENT
condition|)
return|return
name|ngx_add_event
argument_list|(
name|ev
argument_list|,
name|NGX_READ_EVENT
argument_list|,
name|NGX_CLEAR_EVENT
argument_list|)
return|;
else|else
endif|#
directive|endif
return|return
name|ngx_add_event
argument_list|(
name|ev
argument_list|,
name|NGX_READ_EVENT
argument_list|,
name|NGX_LEVEL_EVENT
argument_list|)
return|;
endif|#
directive|endif
comment|/* USE_KQUEUE */
if|#
directive|if
operator|(
name|HAVE_DEFERRED_ACCEPT
operator|)
block|}
endif|#
directive|endif
block|}
end_function

begin_function
DECL|function|ngx_http_init_request (ngx_event_t * ev)
specifier|static
name|int
name|ngx_http_init_request
parameter_list|(
name|ngx_event_t
modifier|*
name|ev
parameter_list|)
block|{
name|ngx_connection_t
modifier|*
name|c
decl_stmt|;
name|ngx_http_server_t
modifier|*
name|srv
decl_stmt|;
name|ngx_http_request_t
modifier|*
name|r
decl_stmt|;
name|c
operator|=
operator|(
name|ngx_connection_t
operator|*
operator|)
name|ev
operator|->
name|data
expr_stmt|;
name|srv
operator|=
operator|(
name|ngx_http_server_t
operator|*
operator|)
name|c
operator|->
name|server
expr_stmt|;
name|ngx_test_null
argument_list|(
name|r
argument_list|,
name|ngx_pcalloc
argument_list|(
name|c
operator|->
name|pool
argument_list|,
sizeof|sizeof
argument_list|(
name|ngx_http_request_t
argument_list|)
argument_list|)
argument_list|,
name|NGX_ERROR
argument_list|)
expr_stmt|;
name|c
operator|->
name|data
operator|=
name|r
expr_stmt|;
name|r
operator|->
name|connection
operator|=
name|c
expr_stmt|;
name|r
operator|->
name|server
operator|=
name|srv
expr_stmt|;
name|r
operator|->
name|srv_conf
operator|=
name|ngx_srv_conf
expr_stmt|;
name|r
operator|->
name|loc_conf
operator|=
name|ngx_loc_conf
expr_stmt|;
if|if
condition|(
name|c
operator|->
name|buffer
operator|==
name|NULL
condition|)
block|{
name|ngx_test_null
argument_list|(
name|c
operator|->
name|buffer
argument_list|,
name|ngx_create_temp_hunk
argument_list|(
name|c
operator|->
name|pool
argument_list|,
name|srv
operator|->
name|header_buffer_size
argument_list|,
literal|0
argument_list|,
literal|0
argument_list|)
argument_list|,
name|NGX_ERROR
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|r
operator|->
name|header_read
operator|=
literal|1
expr_stmt|;
block|}
name|r
operator|->
name|header_in
operator|=
name|c
operator|->
name|buffer
expr_stmt|;
name|ngx_test_null
argument_list|(
name|r
operator|->
name|pool
argument_list|,
name|ngx_create_pool
argument_list|(
name|srv
operator|->
name|request_pool_size
argument_list|,
name|ev
operator|->
name|log
argument_list|)
argument_list|,
name|ngx_http_close_request
argument_list|(
name|r
argument_list|)
argument_list|)
expr_stmt|;
name|ngx_test_null
argument_list|(
name|r
operator|->
name|ctx
argument_list|,
name|ngx_pcalloc
argument_list|(
name|r
operator|->
name|pool
argument_list|,
sizeof|sizeof
argument_list|(
name|void
operator|*
argument_list|)
operator|*
name|ngx_max_module
argument_list|)
argument_list|,
name|ngx_http_close_request
argument_list|(
name|r
argument_list|)
argument_list|)
expr_stmt|;
name|ev
operator|->
name|event_handler
operator|=
name|ngx_http_process_request
expr_stmt|;
name|r
operator|->
name|state_handler
operator|=
name|ngx_http_process_request_line
expr_stmt|;
name|r
operator|->
name|process_header
operator|=
literal|1
expr_stmt|;
name|r
operator|->
name|header_timeout
operator|=
literal|1
expr_stmt|;
return|return
name|ngx_http_process_request
argument_list|(
name|ev
argument_list|)
return|;
block|}
end_function

begin_function
DECL|function|ngx_http_process_request (ngx_event_t * ev)
specifier|static
name|int
name|ngx_http_process_request
parameter_list|(
name|ngx_event_t
modifier|*
name|ev
parameter_list|)
block|{
name|int
name|n
decl_stmt|,
name|rc
decl_stmt|;
name|ngx_connection_t
modifier|*
name|c
decl_stmt|;
name|ngx_http_request_t
modifier|*
name|r
decl_stmt|;
name|ngx_http_log_ctx_t
modifier|*
name|ctx
decl_stmt|;
name|c
operator|=
operator|(
name|ngx_connection_t
operator|*
operator|)
name|ev
operator|->
name|data
expr_stmt|;
name|r
operator|=
operator|(
name|ngx_http_request_t
operator|*
operator|)
name|c
operator|->
name|data
expr_stmt|;
name|ngx_log_debug
argument_list|(
name|ev
operator|->
name|log
argument_list|,
literal|"http process request"
argument_list|)
expr_stmt|;
if|if
condition|(
name|r
operator|->
name|header_read
condition|)
block|{
name|r
operator|->
name|header_read
operator|=
literal|0
expr_stmt|;
name|ngx_log_debug
argument_list|(
argument|ev->log
argument_list|,
literal|"http preread %d"
argument|_                       r->header_in->last.mem - r->header_in->pos.mem
argument_list|)
empty_stmt|;
block|}
else|else
block|{
name|n
operator|=
name|ngx_event_recv
argument_list|(
name|c
argument_list|,
name|r
operator|->
name|header_in
operator|->
name|last
operator|.
name|mem
argument_list|,
name|r
operator|->
name|header_in
operator|->
name|end
operator|-
name|r
operator|->
name|header_in
operator|->
name|last
operator|.
name|mem
argument_list|)
expr_stmt|;
if|if
condition|(
name|n
operator|==
name|NGX_AGAIN
condition|)
block|{
if|if
condition|(
name|r
operator|->
name|header_timeout
condition|)
block|{
name|r
operator|->
name|header_timeout
operator|=
literal|0
expr_stmt|;
name|ngx_del_timer
argument_list|(
name|ev
argument_list|)
expr_stmt|;
name|ngx_add_timer
argument_list|(
name|ev
argument_list|,
name|r
operator|->
name|server
operator|->
name|header_timeout
argument_list|)
expr_stmt|;
block|}
return|return
name|NGX_AGAIN
return|;
block|}
if|if
condition|(
name|n
operator|==
name|NGX_ERROR
condition|)
return|return
name|ngx_http_close_request
argument_list|(
name|r
argument_list|)
return|;
name|ngx_log_debug
argument_list|(
argument|ev->log
argument_list|,
literal|"http read %d"
argument|_ n
argument_list|)
empty_stmt|;
if|if
condition|(
name|n
operator|==
literal|0
condition|)
block|{
if|if
condition|(
name|c
operator|->
name|unexpected_eof
condition|)
name|ngx_log_error
argument_list|(
name|NGX_LOG_INFO
argument_list|,
name|c
operator|->
name|log
argument_list|,
literal|0
argument_list|,
literal|"client prematurely closed connection"
argument_list|)
expr_stmt|;
return|return
name|ngx_http_close_request
argument_list|(
name|r
argument_list|)
return|;
block|}
name|r
operator|->
name|header_in
operator|->
name|last
operator|.
name|mem
operator|+=
name|n
expr_stmt|;
block|}
comment|/* state_handlers are called in following order:         ngx_http_process_request_line(r)         ngx_http_process_request_header(r) */
do|do
block|{
name|rc
operator|=
operator|(
name|r
operator|->
name|state_handler
operator|)
operator|(
name|r
operator|)
expr_stmt|;
if|if
condition|(
name|rc
operator|==
name|NGX_ERROR
condition|)
return|return
name|rc
return|;
comment|/* rc == NGX_OK || rc == NGX_AGAIN */
block|}
do|while
condition|(
name|r
operator|->
name|process_header
operator|&&
name|r
operator|->
name|header_in
operator|->
name|pos
operator|.
name|mem
operator|<
name|r
operator|->
name|header_in
operator|->
name|last
operator|.
name|mem
condition|)
do|;
if|if
condition|(
name|r
operator|->
name|header_timeout
condition|)
block|{
name|r
operator|->
name|header_timeout
operator|=
literal|0
expr_stmt|;
name|ngx_del_timer
argument_list|(
name|ev
argument_list|)
expr_stmt|;
name|ngx_add_timer
argument_list|(
name|ev
argument_list|,
name|r
operator|->
name|server
operator|->
name|header_timeout
argument_list|)
expr_stmt|;
block|}
return|return
name|rc
return|;
block|}
end_function

begin_function
DECL|function|ngx_http_process_request_line (ngx_http_request_t * r)
specifier|static
name|int
name|ngx_http_process_request_line
parameter_list|(
name|ngx_http_request_t
modifier|*
name|r
parameter_list|)
block|{
name|int
name|rc
decl_stmt|;
name|ngx_http_log_ctx_t
modifier|*
name|ctx
decl_stmt|;
name|rc
operator|=
name|ngx_read_http_request_line
argument_list|(
name|r
argument_list|)
expr_stmt|;
if|if
condition|(
name|rc
operator|==
name|NGX_OK
condition|)
block|{
name|ngx_test_null
argument_list|(
name|r
operator|->
name|uri
argument_list|,
name|ngx_palloc
argument_list|(
name|r
operator|->
name|pool
argument_list|,
name|r
operator|->
name|uri_end
operator|-
name|r
operator|->
name|uri_start
operator|+
literal|1
argument_list|)
argument_list|,
name|ngx_http_close_request
argument_list|(
name|r
argument_list|)
argument_list|)
expr_stmt|;
name|ngx_cpystrn
argument_list|(
name|r
operator|->
name|uri
argument_list|,
name|r
operator|->
name|uri_start
argument_list|,
name|r
operator|->
name|uri_end
operator|-
name|r
operator|->
name|uri_start
operator|+
literal|1
argument_list|)
expr_stmt|;
if|if
condition|(
name|r
operator|->
name|uri_ext
condition|)
block|{
name|ngx_test_null
argument_list|(
name|r
operator|->
name|exten
argument_list|,
name|ngx_palloc
argument_list|(
name|r
operator|->
name|pool
argument_list|,
name|r
operator|->
name|uri_end
operator|-
name|r
operator|->
name|uri_ext
operator|+
literal|1
argument_list|)
argument_list|,
name|ngx_http_close_request
argument_list|(
name|r
argument_list|)
argument_list|)
expr_stmt|;
name|ngx_cpystrn
argument_list|(
name|r
operator|->
name|exten
argument_list|,
name|r
operator|->
name|uri_ext
argument_list|,
name|r
operator|->
name|uri_end
operator|-
name|r
operator|->
name|uri_ext
operator|+
literal|1
argument_list|)
expr_stmt|;
block|}
name|ngx_log_debug
argument_list|(
argument|r->connection->log
argument_list|,
literal|"HTTP: %d, %d, %s %s"
argument|_                       r->method _ r->http_version _ r->uri _ r->exten
argument_list|)
empty_stmt|;
if|if
condition|(
name|r
operator|->
name|http_version
operator|==
literal|9
condition|)
return|return
name|ngx_http_event_handler
argument_list|(
name|r
argument_list|)
return|;
comment|/* TODO: check too long URI - no space for header, compact buffer */
name|r
operator|->
name|state_handler
operator|=
name|ngx_http_process_request_header
expr_stmt|;
name|ctx
operator|=
name|r
operator|->
name|connection
operator|->
name|log
operator|->
name|data
expr_stmt|;
name|ctx
operator|->
name|action
operator|=
literal|"reading client request headers"
expr_stmt|;
return|return
name|NGX_OK
return|;
block|}
if|if
condition|(
name|r
operator|->
name|header_in
operator|->
name|last
operator|.
name|mem
operator|>=
name|r
operator|->
name|header_in
operator|->
name|end
condition|)
block|{
name|rc
operator|==
name|NGX_HTTP_PARSE_TOO_LONG_URI
expr_stmt|;
block|}
if|else if
condition|(
name|rc
operator|==
name|NGX_AGAIN
condition|)
block|{
return|return
name|NGX_AGAIN
return|;
block|}
name|ctx
operator|=
name|r
operator|->
name|connection
operator|->
name|log
operator|->
name|data
expr_stmt|;
name|r
operator|->
name|connection
operator|->
name|log
operator|->
name|handler
operator|=
name|NULL
expr_stmt|;
name|ngx_log_error
argument_list|(
name|NGX_LOG_ERR
argument_list|,
name|r
operator|->
name|connection
operator|->
name|log
argument_list|,
literal|0
argument_list|,
name|header_errors
index|[
name|rc
operator|-
name|NGX_HTTP_PARSE_INVALID_METHOD
index|]
argument_list|,
name|ctx
operator|->
name|client
argument_list|)
expr_stmt|;
name|r
operator|->
name|connection
operator|->
name|log
operator|->
name|handler
operator|=
name|ngx_http_log_error
expr_stmt|;
return|return
name|ngx_http_error
argument_list|(
name|r
argument_list|,
operator|(
name|rc
operator|==
name|NGX_HTTP_PARSE_TOO_LONG_URI
operator|)
condition|?
name|NGX_HTTP_REQUEST_URI_TOO_LARGE
else|:
name|NGX_HTTP_BAD_REQUEST
argument_list|)
return|;
block|}
end_function

begin_function
DECL|function|ngx_http_process_request_header (ngx_http_request_t * r)
specifier|static
name|int
name|ngx_http_process_request_header
parameter_list|(
name|ngx_http_request_t
modifier|*
name|r
parameter_list|)
block|{
name|int
name|rc
decl_stmt|;
name|ngx_http_log_ctx_t
modifier|*
name|ctx
decl_stmt|;
for|for
control|(
init|;
condition|;
control|)
block|{
name|rc
operator|=
name|ngx_read_http_header_line
argument_list|(
name|r
argument_list|)
expr_stmt|;
comment|/* TODO: check too long header, compact buffer */
if|if
condition|(
name|rc
operator|==
name|NGX_OK
condition|)
block|{
if|if
condition|(
name|ngx_http_process_request_header_line
argument_list|(
name|r
argument_list|)
operator|==
name|NGX_ERROR
condition|)
return|return
name|ngx_http_error
argument_list|(
name|r
argument_list|,
name|NGX_HTTP_BAD_REQUEST
argument_list|)
return|;
block|}
if|else if
condition|(
name|rc
operator|==
name|NGX_HTTP_PARSE_HEADER_DONE
condition|)
block|{
name|ngx_log_debug
argument_list|(
name|r
operator|->
name|connection
operator|->
name|log
argument_list|,
literal|"HTTP header done"
argument_list|)
expr_stmt|;
return|return
name|ngx_http_event_handler
argument_list|(
name|r
argument_list|)
return|;
block|}
if|else if
condition|(
name|rc
operator|==
name|NGX_AGAIN
condition|)
block|{
return|return
name|NGX_AGAIN
return|;
block|}
if|else if
condition|(
name|rc
operator|==
name|NGX_HTTP_PARSE_INVALID_HEADER
condition|)
block|{
name|ctx
operator|=
name|r
operator|->
name|connection
operator|->
name|log
operator|->
name|data
expr_stmt|;
name|r
operator|->
name|connection
operator|->
name|log
operator|->
name|handler
operator|=
name|NULL
expr_stmt|;
name|ngx_log_error
argument_list|(
name|NGX_LOG_ERR
argument_list|,
name|r
operator|->
name|connection
operator|->
name|log
argument_list|,
literal|0
argument_list|,
literal|"client %s sent invalid header"
argument_list|,
name|ctx
operator|->
name|client
argument_list|)
expr_stmt|;
name|r
operator|->
name|connection
operator|->
name|log
operator|->
name|handler
operator|=
name|ngx_http_log_error
expr_stmt|;
return|return
name|ngx_http_error
argument_list|(
name|r
argument_list|,
name|NGX_HTTP_BAD_REQUEST
argument_list|)
return|;
block|}
block|}
block|}
end_function

begin_function
DECL|function|ngx_http_process_request_header_line (ngx_http_request_t * r)
specifier|static
name|int
name|ngx_http_process_request_header_line
parameter_list|(
name|ngx_http_request_t
modifier|*
name|r
parameter_list|)
block|{
comment|/* STUB */
operator|*
name|r
operator|->
name|header_name_end
operator|=
literal|'\0'
expr_stmt|;
operator|*
name|r
operator|->
name|header_end
operator|=
literal|'\0'
expr_stmt|;
name|ngx_log_debug
argument_list|(
argument|r->connection->log
argument_list|,
literal|"HTTP header: '%s: %s'"
argument|_                   r->header_name_start _ r->header_start
argument_list|)
empty_stmt|;
return|return
name|NGX_OK
return|;
block|}
end_function

begin_comment
comment|/* ******************** */
end_comment

begin_function
DECL|function|ngx_http_discard_body (ngx_http_request_t * r)
name|void
name|ngx_http_discard_body
parameter_list|(
name|ngx_http_request_t
modifier|*
name|r
parameter_list|)
block|{
name|ngx_log_debug
argument_list|(
name|r
operator|->
name|connection
operator|->
name|log
argument_list|,
literal|"set discard body"
argument_list|)
expr_stmt|;
name|ngx_del_timer
argument_list|(
name|r
operator|->
name|connection
operator|->
name|read
argument_list|)
expr_stmt|;
if|if
condition|(
name|r
operator|->
name|client_content_length
condition|)
name|r
operator|->
name|connection
operator|->
name|read
operator|->
name|event_handler
operator|=
name|ngx_http_read_discarded_body
expr_stmt|;
block|}
end_function

begin_function
DECL|function|ngx_http_read_discarded_body (ngx_event_t * ev)
specifier|static
name|int
name|ngx_http_read_discarded_body
parameter_list|(
name|ngx_event_t
modifier|*
name|ev
parameter_list|)
block|{
name|size_t
name|size
decl_stmt|;
name|ssize_t
name|n
decl_stmt|;
name|ngx_connection_t
modifier|*
name|c
decl_stmt|;
name|ngx_http_request_t
modifier|*
name|r
decl_stmt|;
name|c
operator|=
operator|(
name|ngx_connection_t
operator|*
operator|)
name|ev
operator|->
name|data
expr_stmt|;
name|r
operator|=
operator|(
name|ngx_http_request_t
operator|*
operator|)
name|c
operator|->
name|data
expr_stmt|;
name|ngx_log_debug
argument_list|(
name|ev
operator|->
name|log
argument_list|,
literal|"http read discarded body"
argument_list|)
expr_stmt|;
if|if
condition|(
name|ev
operator|->
name|timedout
condition|)
return|return
name|NGX_ERROR
return|;
if|if
condition|(
name|r
operator|->
name|discarded_buffer
operator|==
name|NULL
condition|)
name|ngx_test_null
argument_list|(
name|r
operator|->
name|discarded_buffer
argument_list|,
name|ngx_palloc
argument_list|(
name|r
operator|->
name|pool
argument_list|,
name|r
operator|->
name|server
operator|->
name|discarded_buffer_size
argument_list|)
argument_list|,
name|NGX_ERROR
argument_list|)
expr_stmt|;
name|size
operator|=
name|r
operator|->
name|client_content_length
expr_stmt|;
if|if
condition|(
name|size
operator|>
name|r
operator|->
name|server
operator|->
name|discarded_buffer_size
condition|)
name|size
operator|=
name|r
operator|->
name|server
operator|->
name|discarded_buffer_size
expr_stmt|;
name|n
operator|=
name|ngx_event_recv
argument_list|(
name|c
argument_list|,
name|r
operator|->
name|discarded_buffer
argument_list|,
name|size
argument_list|)
expr_stmt|;
if|if
condition|(
name|n
operator|==
name|NGX_ERROR
condition|)
return|return
name|NGX_ERROR
return|;
if|if
condition|(
name|n
operator|==
name|NGX_AGAIN
condition|)
return|return
name|NGX_OK
return|;
name|r
operator|->
name|client_content_length
operator|-=
name|n
expr_stmt|;
comment|/* XXX: what if r->client_content_length == 0 ? */
return|return
name|NGX_OK
return|;
block|}
end_function

begin_function
DECL|function|ngx_http_discarded_read (ngx_event_t * ev)
specifier|static
name|int
name|ngx_http_discarded_read
parameter_list|(
name|ngx_event_t
modifier|*
name|ev
parameter_list|)
block|{
name|ssize_t
name|n
decl_stmt|;
name|ngx_connection_t
modifier|*
name|c
decl_stmt|;
name|ngx_http_request_t
modifier|*
name|r
decl_stmt|;
name|c
operator|=
operator|(
name|ngx_connection_t
operator|*
operator|)
name|ev
operator|->
name|data
expr_stmt|;
name|r
operator|=
operator|(
name|ngx_http_request_t
operator|*
operator|)
name|c
operator|->
name|data
expr_stmt|;
name|ngx_log_debug
argument_list|(
name|ev
operator|->
name|log
argument_list|,
literal|"http discarded read"
argument_list|)
expr_stmt|;
if|if
condition|(
name|ev
operator|->
name|timedout
condition|)
return|return
name|NGX_ERROR
return|;
if|if
condition|(
name|r
operator|->
name|discarded_buffer
operator|==
name|NULL
condition|)
name|ngx_test_null
argument_list|(
name|r
operator|->
name|discarded_buffer
argument_list|,
name|ngx_palloc
argument_list|(
name|r
operator|->
name|pool
argument_list|,
name|r
operator|->
name|server
operator|->
name|discarded_buffer_size
argument_list|)
argument_list|,
name|NGX_ERROR
argument_list|)
expr_stmt|;
name|n
operator|=
name|ngx_event_recv
argument_list|(
name|c
argument_list|,
name|r
operator|->
name|discarded_buffer
argument_list|,
name|r
operator|->
name|server
operator|->
name|discarded_buffer_size
argument_list|)
expr_stmt|;
return|return
name|n
return|;
block|}
end_function

begin_comment
comment|/* ******************** */
end_comment

begin_function
DECL|function|ngx_http_event_handler (ngx_http_request_t * r)
specifier|static
name|int
name|ngx_http_event_handler
parameter_list|(
name|ngx_http_request_t
modifier|*
name|r
parameter_list|)
block|{
name|int
name|rc
decl_stmt|;
name|ngx_msec_t
name|timeout
decl_stmt|;
name|rc
operator|=
name|ngx_http_handler
argument_list|(
name|r
argument_list|)
expr_stmt|;
comment|/* transfer not completed */
if|if
condition|(
name|rc
operator|==
name|NGX_AGAIN
condition|)
block|{
if|#
directive|if
operator|(
name|HAVE_CLEAR_EVENT
operator|)
if|if
condition|(
name|ngx_add_event
argument_list|(
name|r
operator|->
name|connection
operator|->
name|write
argument_list|,
name|NGX_WRITE_EVENT
argument_list|,
name|NGX_CLEAR_EVENT
argument_list|)
operator|==
name|NGX_ERROR
condition|)
block|{
else|#
directive|else
if|if
condition|(
name|ngx_add_event
argument_list|(
name|r
operator|->
name|connection
operator|->
name|write
argument_list|,
name|NGX_WRITE_EVENT
argument_list|,
name|NGX_ONESHOT_EVENT
argument_list|)
operator|==
name|NGX_ERROR
condition|)
block|{
endif|#
directive|endif
return|return
name|ngx_http_close_request
argument_list|(
name|r
argument_list|)
return|;
block|}
if|if
condition|(
name|r
operator|->
name|connection
operator|->
name|sent
operator|>
literal|0
condition|)
block|{
name|ngx_log_debug
argument_list|(
argument|r->connection->log
argument_list|,
literal|"sent: "
argument|QD_FMT _                           r->connection->sent
argument_list|)
empty_stmt|;
name|timeout
operator|=
operator|(
name|ngx_msec_t
operator|)
operator|(
name|r
operator|->
name|connection
operator|->
name|sent
operator|*
literal|10
operator|)
expr_stmt|;
name|ngx_log_debug
argument_list|(
argument|r->connection->log
argument_list|,
literal|"timeout: %d"
argument|_ timeout
argument_list|)
empty_stmt|;
name|ngx_add_timer
argument_list|(
name|r
operator|->
name|connection
operator|->
name|write
argument_list|,
name|timeout
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|ngx_add_timer
argument_list|(
name|r
operator|->
name|connection
operator|->
name|write
argument_list|,
literal|10000
argument_list|)
expr_stmt|;
block|}
name|r
operator|->
name|connection
operator|->
name|write
operator|->
name|event_handler
operator|=
name|ngx_http_writer
expr_stmt|;
return|return
name|rc
return|;
block|}
if|if
condition|(
name|rc
operator|==
name|NGX_ERROR
condition|)
block|{
comment|/* log http request */
return|return
name|ngx_http_close_request
argument_list|(
name|r
argument_list|)
return|;
block|}
if|if
condition|(
name|rc
operator|>=
name|NGX_HTTP_SPECIAL_RESPONSE
condition|)
return|return
name|ngx_http_special_response
argument_list|(
name|r
argument_list|,
name|rc
argument_list|)
return|;
comment|/* rc == NGX_OK */
if|if
condition|(
operator|!
name|r
operator|->
name|keepalive
condition|)
block|{
if|if
condition|(
name|r
operator|->
name|lingering_close
condition|)
block|{
return|return
name|ngx_http_set_lingering_close
argument_list|(
name|r
argument_list|)
return|;
block|}
else|else
block|{
return|return
name|ngx_http_close_request
argument_list|(
name|r
argument_list|)
return|;
block|}
block|}
comment|/* keepalive */
name|ngx_http_close_request
argument_list|(
name|r
argument_list|)
expr_stmt|;
name|r
operator|->
name|connection
operator|->
name|buffer
operator|->
name|pos
operator|.
name|mem
operator|=
name|r
operator|->
name|connection
operator|->
name|buffer
operator|->
name|last
operator|.
name|mem
operator|=
name|r
operator|->
name|connection
operator|->
name|buffer
operator|->
name|start
expr_stmt|;
name|r
operator|->
name|connection
operator|->
name|read
operator|->
name|event_handler
operator|=
name|ngx_http_keepalive_handler
expr_stmt|;
block|}
DECL|function|ngx_http_handler (ngx_http_request_t * r)
specifier|static
name|int
name|ngx_http_handler
parameter_list|(
name|ngx_http_request_t
modifier|*
name|r
parameter_list|)
block|{
name|int
name|rc
decl_stmt|;
name|ngx_del_timer
argument_list|(
name|r
operator|->
name|connection
operator|->
name|read
argument_list|)
expr_stmt|;
name|r
operator|->
name|header_timeout
operator|=
literal|0
expr_stmt|;
name|r
operator|->
name|process_header
operator|=
literal|0
expr_stmt|;
name|r
operator|->
name|state_handler
operator|=
name|NULL
expr_stmt|;
name|r
operator|->
name|connection
operator|->
name|unexpected_eof
operator|=
literal|0
expr_stmt|;
name|r
operator|->
name|lingering_close
operator|=
literal|1
expr_stmt|;
name|r
operator|->
name|connection
operator|->
name|read
operator|->
name|event_handler
operator|=
name|ngx_http_block_read
expr_stmt|;
comment|/* STUB: should find handler */
if|#
directive|if
literal|0
block_content|r->filter = NGX_HTTP_FILTER_NEED_IN_MEMORY;
endif|#
directive|endif
name|rc
operator|=
name|ngx_http_set_default_handler
argument_list|(
name|r
argument_list|)
expr_stmt|;
if|if
condition|(
name|rc
operator|>=
name|NGX_HTTP_SPECIAL_RESPONSE
condition|)
return|return
name|ngx_http_special_response
argument_list|(
name|r
argument_list|,
name|rc
argument_list|)
return|;
name|rc
operator|=
name|r
operator|->
name|handler
argument_list|(
name|r
argument_list|)
expr_stmt|;
return|return
name|rc
return|;
block|}
DECL|function|ngx_http_internal_redirect (ngx_http_request_t * r,char * uri)
name|int
name|ngx_http_internal_redirect
parameter_list|(
name|ngx_http_request_t
modifier|*
name|r
parameter_list|,
name|char
modifier|*
name|uri
parameter_list|)
block|{
name|ngx_log_debug
argument_list|(
argument|r->connection->log
argument_list|,
literal|"internal redirect: '%s'"
argument|_ uri
argument_list|)
empty_stmt|;
name|r
operator|->
name|uri
operator|=
name|uri
expr_stmt|;
name|r
operator|->
name|uri_start
operator|=
name|uri
expr_stmt|;
name|r
operator|->
name|uri_end
operator|=
name|uri
operator|+
name|strlen
argument_list|(
name|uri
argument_list|)
expr_stmt|;
return|return
name|ngx_http_handler
argument_list|(
name|r
argument_list|)
return|;
block|}
DECL|function|ngx_http_set_default_handler (ngx_http_request_t * r)
specifier|static
name|int
name|ngx_http_set_default_handler
parameter_list|(
name|ngx_http_request_t
modifier|*
name|r
parameter_list|)
block|{
name|int
name|err
decl_stmt|,
name|rc
decl_stmt|;
name|char
modifier|*
name|name
decl_stmt|,
modifier|*
name|loc
decl_stmt|,
modifier|*
name|file
decl_stmt|;
name|ngx_test_null
argument_list|(
name|r
operator|->
name|headers_out
argument_list|,
name|ngx_pcalloc
argument_list|(
name|r
operator|->
name|pool
argument_list|,
sizeof|sizeof
argument_list|(
name|ngx_http_headers_out_t
argument_list|)
argument_list|)
argument_list|,
name|NGX_HTTP_INTERNAL_SERVER_ERROR
argument_list|)
expr_stmt|;
if|if
condition|(
operator|*
operator|(
name|r
operator|->
name|uri_end
operator|-
literal|1
operator|)
operator|==
literal|'/'
condition|)
block|{
name|r
operator|->
name|handler
operator|=
name|ngx_http_index_handler
expr_stmt|;
return|return
name|NGX_OK
return|;
block|}
comment|/* 20 bytes is spare space for some index name, i.e. index.html */
name|r
operator|->
name|filename_len
operator|=
name|r
operator|->
name|uri_end
operator|-
name|r
operator|->
name|uri_start
operator|+
name|r
operator|->
name|server
operator|->
name|doc_root_len
operator|+
literal|20
expr_stmt|;
name|ngx_test_null
argument_list|(
name|r
operator|->
name|filename
argument_list|,
name|ngx_palloc
argument_list|(
name|r
operator|->
name|pool
argument_list|,
name|r
operator|->
name|filename_len
argument_list|)
argument_list|,
name|NGX_HTTP_INTERNAL_SERVER_ERROR
argument_list|)
expr_stmt|;
name|r
operator|->
name|location
operator|=
name|ngx_cpystrn
argument_list|(
name|r
operator|->
name|filename
argument_list|,
name|r
operator|->
name|server
operator|->
name|doc_root
argument_list|,
name|r
operator|->
name|server
operator|->
name|doc_root_len
argument_list|)
expr_stmt|;
name|file
operator|=
name|ngx_cpystrn
argument_list|(
name|r
operator|->
name|location
argument_list|,
name|r
operator|->
name|uri_start
argument_list|,
name|r
operator|->
name|uri_end
operator|-
name|r
operator|->
name|uri_start
operator|+
literal|1
argument_list|)
expr_stmt|;
name|ngx_log_debug
argument_list|(
argument|r->connection->log
argument_list|,
literal|"HTTP filename: '%s'"
argument|_ r->filename
argument_list|)
empty_stmt|;
if|if
condition|(
name|ngx_file_type
argument_list|(
name|r
operator|->
name|filename
argument_list|,
operator|&
name|r
operator|->
name|fileinfo
argument_list|)
operator|==
operator|-
literal|1
condition|)
block|{
name|err
operator|=
name|ngx_errno
expr_stmt|;
name|ngx_log_error
argument_list|(
name|NGX_LOG_ERR
argument_list|,
name|r
operator|->
name|connection
operator|->
name|log
argument_list|,
name|err
argument_list|,
name|ngx_file_type_n
literal|" %s failed"
argument_list|,
name|r
operator|->
name|filename
argument_list|)
expr_stmt|;
if|if
condition|(
name|err
operator|==
name|NGX_ENOENT
condition|)
return|return
name|NGX_HTTP_NOT_FOUND
return|;
else|else
return|return
name|NGX_HTTP_INTERNAL_SERVER_ERROR
return|;
block|}
if|if
condition|(
name|ngx_is_dir
argument_list|(
name|r
operator|->
name|fileinfo
argument_list|)
condition|)
block|{
name|ngx_log_debug
argument_list|(
argument|r->connection->log
argument_list|,
literal|"HTTP DIR: '%s'"
argument|_ r->filename
argument_list|)
empty_stmt|;
operator|*
name|file
operator|++
operator|=
literal|'/'
expr_stmt|;
operator|*
name|file
operator|=
literal|'\0'
expr_stmt|;
name|r
operator|->
name|headers_out
operator|->
name|location
operator|=
name|r
operator|->
name|location
expr_stmt|;
return|return
name|NGX_HTTP_MOVED_PERMANENTLY
return|;
block|}
name|r
operator|->
name|handler
operator|=
name|ngx_http_static_handler
expr_stmt|;
return|return
name|NGX_OK
return|;
block|}
DECL|function|ngx_http_block_read (ngx_event_t * ev)
specifier|static
name|int
name|ngx_http_block_read
parameter_list|(
name|ngx_event_t
modifier|*
name|ev
parameter_list|)
block|{
name|ngx_log_debug
argument_list|(
name|ev
operator|->
name|log
argument_list|,
literal|"http read blocked"
argument_list|)
expr_stmt|;
name|ev
operator|->
name|blocked
operator|=
literal|1
expr_stmt|;
return|return
name|ngx_del_event
argument_list|(
name|ev
argument_list|,
name|NGX_READ_EVENT
argument_list|)
return|;
block|}
DECL|function|ngx_http_writer (ngx_event_t * ev)
specifier|static
name|int
name|ngx_http_writer
parameter_list|(
name|ngx_event_t
modifier|*
name|ev
parameter_list|)
block|{
name|int
name|rc
decl_stmt|;
name|ngx_msec_t
name|timeout
decl_stmt|;
name|ngx_connection_t
modifier|*
name|c
decl_stmt|;
name|ngx_http_request_t
modifier|*
name|r
decl_stmt|;
name|ngx_http_core_conf_t
modifier|*
name|conf
decl_stmt|;
name|c
operator|=
operator|(
name|ngx_connection_t
operator|*
operator|)
name|ev
operator|->
name|data
expr_stmt|;
name|r
operator|=
operator|(
name|ngx_http_request_t
operator|*
operator|)
name|c
operator|->
name|data
expr_stmt|;
name|c
operator|->
name|sent
operator|=
literal|0
expr_stmt|;
name|rc
operator|=
name|ngx_http_output_filter
argument_list|(
name|r
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
name|ngx_log_debug
argument_list|(
argument|ev->log
argument_list|,
literal|"output filter in writer: %d"
argument|_ rc
argument_list|)
empty_stmt|;
if|if
condition|(
name|rc
operator|==
name|NGX_AGAIN
condition|)
block|{
if|if
condition|(
name|c
operator|->
name|sent
operator|>
literal|0
condition|)
block|{
name|conf
operator|=
operator|(
name|ngx_http_core_conf_t
operator|*
operator|)
name|ngx_get_module_loc_conf
argument_list|(
name|r
operator|->
expr|main
operator|?
name|r
operator|->
expr|main
operator|:
name|r
argument_list|,
name|ngx_http_core_module
argument_list|)
expr_stmt|;
name|timeout
operator|=
operator|(
name|ngx_msec_t
operator|)
operator|(
name|c
operator|->
name|sent
operator|*
name|conf
operator|->
name|send_timeout
operator|)
expr_stmt|;
name|ngx_log_debug
argument_list|(
argument|ev->log
argument_list|,
literal|"sent: "
argument|QD_FMT _ c->sent
argument_list|)
empty_stmt|;
name|ngx_log_debug
argument_list|(
argument|ev->log
argument_list|,
literal|"timeout: %d"
argument|_ timeout
argument_list|)
empty_stmt|;
name|ngx_del_timer
argument_list|(
name|ev
argument_list|)
expr_stmt|;
name|ngx_add_timer
argument_list|(
name|ev
argument_list|,
name|timeout
argument_list|)
expr_stmt|;
block|}
if|if
condition|(
name|ev
operator|->
name|oneshot
condition|)
if|if
condition|(
name|ngx_add_event
argument_list|(
name|r
operator|->
name|connection
operator|->
name|write
argument_list|,
name|NGX_WRITE_EVENT
argument_list|,
name|NGX_ONESHOT_EVENT
argument_list|)
operator|==
name|NGX_ERROR
condition|)
block|{
return|return
name|ngx_http_close_request
argument_list|(
name|r
argument_list|)
return|;
block|}
return|return
name|rc
return|;
block|}
if|if
condition|(
name|rc
operator|==
name|NGX_ERROR
condition|)
return|return
name|rc
return|;
comment|/* rc == NGX_OK */
name|ngx_log_debug
argument_list|(
name|ev
operator|->
name|log
argument_list|,
literal|"http writer done"
argument_list|)
expr_stmt|;
if|if
condition|(
operator|!
name|r
operator|->
name|keepalive
condition|)
block|{
if|if
condition|(
name|r
operator|->
name|lingering_close
condition|)
block|{
name|ngx_http_set_lingering_close
argument_list|(
name|r
argument_list|)
expr_stmt|;
block|}
else|else
block|{
return|return
name|ngx_http_close_request
argument_list|(
name|r
argument_list|)
return|;
block|}
block|}
comment|/* keepalive */
name|ngx_http_close_request
argument_list|(
name|r
argument_list|)
expr_stmt|;
name|c
operator|->
name|buffer
operator|->
name|pos
operator|.
name|mem
operator|=
name|c
operator|->
name|buffer
operator|->
name|last
operator|.
name|mem
operator|=
name|c
operator|->
name|buffer
operator|->
name|start
expr_stmt|;
name|c
operator|->
name|read
operator|->
name|event_handler
operator|=
name|ngx_http_keepalive_handler
expr_stmt|;
block|}
DECL|function|ngx_http_set_lingering_close (ngx_http_request_t * r)
specifier|static
name|int
name|ngx_http_set_lingering_close
parameter_list|(
name|ngx_http_request_t
modifier|*
name|r
parameter_list|)
block|{
name|r
operator|->
name|lingering_time
operator|=
name|ngx_time
argument_list|()
operator|+
name|r
operator|->
name|server
operator|->
name|lingering_time
expr_stmt|;
name|r
operator|->
name|connection
operator|->
name|read
operator|->
name|event_handler
operator|=
name|ngx_http_lingering_close
expr_stmt|;
name|ngx_del_timer
argument_list|(
name|r
operator|->
name|connection
operator|->
name|read
argument_list|)
expr_stmt|;
name|ngx_add_timer
argument_list|(
name|r
operator|->
name|connection
operator|->
name|read
argument_list|,
name|r
operator|->
name|server
operator|->
name|lingering_timeout
argument_list|)
expr_stmt|;
if|#
directive|if
operator|(
name|HAVE_CLEAR_EVENT
operator|)
if|if
condition|(
name|ngx_add_event
argument_list|(
name|r
operator|->
name|connection
operator|->
name|read
argument_list|,
name|NGX_READ_EVENT
argument_list|,
name|NGX_CLEAR_EVENT
argument_list|)
operator|==
name|NGX_ERROR
condition|)
block|{
else|#
directive|else
if|if
condition|(
name|ngx_add_event
argument_list|(
name|r
operator|->
name|connection
operator|->
name|read
argument_list|,
name|NGX_READ_EVENT
argument_list|,
name|NGX_ONESHOT_EVENT
argument_list|)
operator|==
name|NGX_ERROR
condition|)
block|{
endif|#
directive|endif
return|return
name|ngx_http_close_request
argument_list|(
name|r
argument_list|)
return|;
block|}
if|if
condition|(
name|ngx_shutdown_socket
argument_list|(
name|r
operator|->
name|connection
operator|->
name|fd
argument_list|,
name|NGX_WRITE_SHUTDOWN
argument_list|)
operator|==
name|NGX_ERROR
condition|)
block|{
name|ngx_log_error
argument_list|(
name|NGX_LOG_ERR
argument_list|,
name|r
operator|->
name|connection
operator|->
name|log
argument_list|,
name|ngx_socket_errno
argument_list|,
name|ngx_shutdown_socket_n
literal|" failed"
argument_list|)
expr_stmt|;
return|return
name|ngx_http_close_request
argument_list|(
name|r
argument_list|)
return|;
block|}
return|return
name|NGX_OK
return|;
block|}
DECL|function|ngx_http_keepalive_handler (ngx_event_t * ev)
specifier|static
name|int
name|ngx_http_keepalive_handler
parameter_list|(
name|ngx_event_t
modifier|*
name|ev
parameter_list|)
block|{
name|ssize_t
name|n
decl_stmt|;
name|ngx_connection_t
modifier|*
name|c
decl_stmt|;
name|ngx_http_log_ctx_t
modifier|*
name|ctx
decl_stmt|;
name|c
operator|=
operator|(
name|ngx_connection_t
operator|*
operator|)
name|ev
operator|->
name|data
expr_stmt|;
name|ngx_log_debug
argument_list|(
name|ev
operator|->
name|log
argument_list|,
literal|"http keepalive"
argument_list|)
expr_stmt|;
if|if
condition|(
name|ev
operator|->
name|timedout
condition|)
return|return
name|NGX_DONE
return|;
name|n
operator|=
name|ngx_event_recv
argument_list|(
name|c
argument_list|,
name|c
operator|->
name|buffer
operator|->
name|last
operator|.
name|mem
argument_list|,
name|c
operator|->
name|buffer
operator|->
name|end
operator|-
name|c
operator|->
name|buffer
operator|->
name|last
operator|.
name|mem
argument_list|)
expr_stmt|;
if|if
condition|(
name|n
operator|==
name|NGX_AGAIN
operator|||
name|n
operator|==
name|NGX_ERROR
condition|)
return|return
name|n
return|;
name|ctx
operator|=
operator|(
name|ngx_http_log_ctx_t
operator|*
operator|)
name|ev
operator|->
name|log
operator|->
name|data
expr_stmt|;
name|ev
operator|->
name|log
operator|->
name|handler
operator|=
name|NULL
expr_stmt|;
if|if
condition|(
name|n
operator|==
literal|0
condition|)
block|{
name|ngx_log_error
argument_list|(
name|NGX_LOG_INFO
argument_list|,
name|ev
operator|->
name|log
argument_list|,
literal|0
argument_list|,
literal|"client %s closed keepalive connection"
argument_list|,
name|ctx
operator|->
name|client
argument_list|)
expr_stmt|;
return|return
name|NGX_DONE
return|;
block|}
name|c
operator|->
name|buffer
operator|->
name|last
operator|.
name|mem
operator|+=
name|n
expr_stmt|;
name|ev
operator|->
name|log
operator|->
name|handler
operator|=
name|ngx_http_log_error
expr_stmt|;
name|ctx
operator|->
name|action
operator|=
literal|"reading client request line"
expr_stmt|;
return|return
name|ngx_http_init_request
argument_list|(
name|ev
argument_list|)
return|;
block|}
DECL|function|ngx_http_lingering_close (ngx_event_t * ev)
specifier|static
name|int
name|ngx_http_lingering_close
parameter_list|(
name|ngx_event_t
modifier|*
name|ev
parameter_list|)
block|{
name|ssize_t
name|n
decl_stmt|;
name|ngx_msec_t
name|timer
decl_stmt|;
name|ngx_connection_t
modifier|*
name|c
decl_stmt|;
name|ngx_http_request_t
modifier|*
name|r
decl_stmt|;
name|c
operator|=
operator|(
name|ngx_connection_t
operator|*
operator|)
name|ev
operator|->
name|data
expr_stmt|;
name|r
operator|=
operator|(
name|ngx_http_request_t
operator|*
operator|)
name|c
operator|->
name|data
expr_stmt|;
name|ngx_log_debug
argument_list|(
name|ev
operator|->
name|log
argument_list|,
literal|"http lingering close"
argument_list|)
expr_stmt|;
if|if
condition|(
name|ev
operator|->
name|timedout
condition|)
return|return
name|NGX_DONE
return|;
name|timer
operator|=
name|r
operator|->
name|lingering_time
operator|-
name|ngx_time
argument_list|()
expr_stmt|;
if|if
condition|(
name|timer
operator|<=
literal|0
condition|)
return|return
name|NGX_DONE
return|;
if|if
condition|(
name|r
operator|->
name|discarded_buffer
operator|==
name|NULL
condition|)
block|{
if|if
condition|(
name|r
operator|->
name|header_in
operator|->
name|end
operator|-
name|r
operator|->
name|header_in
operator|->
name|last
operator|.
name|mem
operator|>=
name|r
operator|->
name|server
operator|->
name|discarded_buffer_size
condition|)
block|{
name|r
operator|->
name|discarded_buffer
operator|=
name|r
operator|->
name|header_in
operator|->
name|last
operator|.
name|mem
expr_stmt|;
block|}
else|else
block|{
name|ngx_test_null
argument_list|(
name|r
operator|->
name|discarded_buffer
argument_list|,
name|ngx_palloc
argument_list|(
name|c
operator|->
name|pool
argument_list|,
name|r
operator|->
name|server
operator|->
name|discarded_buffer_size
argument_list|)
argument_list|,
name|NGX_ERROR
argument_list|)
expr_stmt|;
block|}
block|}
name|n
operator|=
name|ngx_event_recv
argument_list|(
name|c
argument_list|,
name|r
operator|->
name|discarded_buffer
argument_list|,
name|r
operator|->
name|server
operator|->
name|discarded_buffer_size
argument_list|)
expr_stmt|;
if|if
condition|(
name|n
operator|==
name|NGX_ERROR
condition|)
return|return
name|NGX_ERROR
return|;
if|if
condition|(
name|n
operator|==
literal|0
condition|)
return|return
name|NGX_DONE
return|;
name|timer
operator|*=
literal|1000
expr_stmt|;
if|if
condition|(
name|timer
operator|>
name|r
operator|->
name|server
operator|->
name|lingering_timeout
condition|)
name|timer
operator|=
name|r
operator|->
name|server
operator|->
name|lingering_timeout
expr_stmt|;
name|ngx_del_timer
argument_list|(
name|ev
argument_list|)
expr_stmt|;
name|ngx_add_timer
argument_list|(
name|ev
argument_list|,
name|timer
argument_list|)
expr_stmt|;
return|return
name|NGX_OK
return|;
block|}
DECL|function|ngx_http_special_response (ngx_http_request_t * r,int error)
specifier|static
name|int
name|ngx_http_special_response
parameter_list|(
name|ngx_http_request_t
modifier|*
name|r
parameter_list|,
name|int
name|error
parameter_list|)
block|{
return|return
name|ngx_http_error
argument_list|(
name|r
argument_list|,
name|error
argument_list|)
return|;
block|}
DECL|function|ngx_http_redirect (ngx_http_request_t * r,int redirect)
specifier|static
name|int
name|ngx_http_redirect
parameter_list|(
name|ngx_http_request_t
modifier|*
name|r
parameter_list|,
name|int
name|redirect
parameter_list|)
block|{
comment|/* STUB */
comment|/* log request */
return|return
name|ngx_http_close_request
argument_list|(
name|r
argument_list|)
return|;
block|}
DECL|function|ngx_http_error (ngx_http_request_t * r,int error)
specifier|static
name|int
name|ngx_http_error
parameter_list|(
name|ngx_http_request_t
modifier|*
name|r
parameter_list|,
name|int
name|error
parameter_list|)
block|{
comment|/* STUB */
name|ngx_log_debug
argument_list|(
argument|r->connection->log
argument_list|,
literal|"http error: %d"
argument|_ error
argument_list|)
empty_stmt|;
comment|/* log request */
return|return
name|ngx_http_close_request
argument_list|(
name|r
argument_list|)
return|;
block|}
if|#
directive|if
literal|0
block_content|static int ngx_process_http_request(ngx_http_request_t *r) {     int fd;     struct stat sb;     ngx_http_header_out_t  *header_out;     ngx_chunk_t            *header, *ch;      int index = (*(r->uri_end - 1) == '/') ? sizeof(NGX_INDEX) : 1;     char *name = ngx_palloc(r->pool,                            r->uri_end - r->uri_start + strlen(ngx_root) + index);     strcpy(name, ngx_root);     strcat(name, r->uri_start);     if (*(r->uri_end - 1) == '/')         strcat(name, NGX_INDEX);      ngx_log_debug(r->connection->log, "HTTP URI: '%s'", name);      if ((fd = open(name, O_RDONLY)) == -1) {         ngx_log_error(NGX_LOG_ERR, r->connection->log, errno,                      "open %s failed", name);         return -1;     }      if (fstat(fd,&sb) == -1) {         ngx_log_error(NGX_LOG_ERR, r->connection->log, errno,                      "fstat %s failed", name);         return -1;     }      header_out = ngx_palloc(r->pool, sizeof(ngx_http_header_out_t));      header_out->status = NGX_HTTP_OK;     header_out->content_length = sb.st_size;     header_out->last_modified = sb.st_mtime;     header_out->content_type = "text/html";     header_out->charset = "koi8-r";     header_out->date = time(NULL);     header_out->connection = NGX_HTTP_CONN_CLOSE;
comment|/*     header_out->connection = NGX_HTTP_CONN_KEEP_ALIVE;     r->connection->read->event_handler = ngx_http_init_request; */
block_content|header = ngx_http_header(r, header_out);     ch = ngx_palloc(r->pool, sizeof(ngx_chunk_t));     ch->ident = fd;     ch->offset = 0;     ch->size = sb.st_size;     ch->next = NULL;     header->next = ch;      ngx_event_write(r->connection, header);      return 0; }
endif|#
directive|endif
DECL|function|ngx_http_close_request (ngx_http_request_t * r)
specifier|static
name|int
name|ngx_http_close_request
parameter_list|(
name|ngx_http_request_t
modifier|*
name|r
parameter_list|)
block|{
comment|/*     if (r->logging)         ngx_http_log_request(r); */
name|ngx_destroy_pool
argument_list|(
name|r
operator|->
name|pool
argument_list|)
expr_stmt|;
name|ngx_log_debug
argument_list|(
name|r
operator|->
name|connection
operator|->
name|log
argument_list|,
literal|"http close"
argument_list|)
expr_stmt|;
name|ngx_del_timer
argument_list|(
name|r
operator|->
name|connection
operator|->
name|read
argument_list|)
expr_stmt|;
name|ngx_del_timer
argument_list|(
name|r
operator|->
name|connection
operator|->
name|write
argument_list|)
expr_stmt|;
return|return
name|NGX_DONE
return|;
block|}
DECL|function|ngx_http_log_error (void * data,char * buf,size_t len)
specifier|static
name|size_t
name|ngx_http_log_error
parameter_list|(
name|void
modifier|*
name|data
parameter_list|,
name|char
modifier|*
name|buf
parameter_list|,
name|size_t
name|len
parameter_list|)
block|{
name|ngx_http_log_ctx_t
modifier|*
name|ctx
init|=
operator|(
name|ngx_http_log_ctx_t
operator|*
operator|)
name|data
decl_stmt|;
if|if
condition|(
name|ctx
operator|->
name|url
condition|)
return|return
name|ngx_snprintf
argument_list|(
name|buf
argument_list|,
name|len
argument_list|,
literal|" while %s, client: %s, URL: %s"
argument_list|,
name|ctx
operator|->
name|action
argument_list|,
name|ctx
operator|->
name|client
argument_list|,
name|ctx
operator|->
name|url
argument_list|)
return|;
else|else
return|return
name|ngx_snprintf
argument_list|(
name|buf
argument_list|,
name|len
argument_list|,
literal|" while %s, client: %s"
argument_list|,
name|ctx
operator|->
name|action
argument_list|,
name|ctx
operator|->
name|client
argument_list|)
return|;
block|}
end_function

end_unit

