begin_unit|revision:1.0.0;language:C;cregit-version:0.0.1
begin_include
include|#
directive|include
file|<ngx_os_thread.h>
end_include

begin_decl_stmt
DECL|variable|ngx_stacks_start
name|char
modifier|*
name|ngx_stacks_start
decl_stmt|;
end_decl_stmt

begin_decl_stmt
DECL|variable|ngx_stacks_end
name|char
modifier|*
name|ngx_stacks_end
decl_stmt|;
end_decl_stmt

begin_decl_stmt
DECL|variable|ngx_stack_size
name|size_t
name|ngx_stack_size
decl_stmt|;
end_decl_stmt

begin_comment
comment|/* handle thread-safe errno */
end_comment

begin_decl_stmt
DECL|variable|errno0
specifier|static
name|int
name|errno0
decl_stmt|;
end_decl_stmt

begin_comment
DECL|variable|errno0
comment|/* errno for main thread */
end_comment

begin_decl_stmt
DECL|variable|errnos
specifier|static
name|int
modifier|*
name|errnos
decl_stmt|;
end_decl_stmt

begin_function
DECL|function|__error ()
name|int
modifier|*
name|__error
parameter_list|()
block|{
name|ngx_tid_t
name|tid
init|=
name|ngx_gettid
argument_list|()
decl_stmt|;
return|return
name|tid
condition|?
operator|&
operator|(
name|errnos
index|[
name|ngx_gettid
argument_list|()
index|]
operator|)
else|:
operator|&
name|errno0
return|;
block|}
end_function

begin_function
DECL|function|ngx_create_thread (ngx_os_tid_t * tid,void * stack,int (* func)(void * arg),void * arg,ngx_log_t log)
name|int
name|ngx_create_thread
parameter_list|(
name|ngx_os_tid_t
modifier|*
name|tid
parameter_list|,
name|void
modifier|*
name|stack
parameter_list|,
name|int
function_decl|(
modifier|*
name|func
function_decl|)
parameter_list|(
name|void
modifier|*
name|arg
parameter_list|)
parameter_list|,
name|void
modifier|*
name|arg
parameter_list|,
name|ngx_log_t
name|log
parameter_list|)
block|{
name|int
name|id
decl_stmt|,
name|err
decl_stmt|;
name|id
operator|=
name|rfork_thread
argument_list|(
name|RFPROC
operator||
name|RFMEM
argument_list|,
name|stack
argument_list|,
name|func
argument_list|,
name|arg
argument_list|)
expr_stmt|;
name|err
operator|=
name|ngx_errno
expr_stmt|;
if|if
condition|(
name|id
operator|==
operator|-
literal|1
condition|)
name|ngx_log_error
argument_list|(
name|NGX_LOG_ERR
argument_list|,
name|log
argument_list|,
name|err
argument_list|,
literal|"ngx_create_os_thread: rfork failed"
argument_list|)
expr_stmt|;
else|else
operator|*
name|tid
operator|=
name|id
expr_stmt|;
return|return
name|err
return|;
block|}
end_function

begin_function
DECL|function|ngx_create_thread_env (int n,size_t size,ngx_log_t log)
name|int
name|ngx_create_thread_env
parameter_list|(
name|int
name|n
parameter_list|,
name|size_t
name|size
parameter_list|,
name|ngx_log_t
name|log
parameter_list|)
block|{
name|char
modifier|*
name|addr
decl_stmt|;
comment|/* create thread stacks */
name|addr
operator|=
name|mmap
argument_list|(
name|NULL
argument_list|,
name|n
operator|*
name|size
argument_list|,
name|PROT_READ
operator||
name|PROT_WRITE
argument_list|,
name|MAP_ANON
argument_list|,
operator|-
literal|1
argument_list|,
name|NULL
argument_list|)
expr_stmt|;
if|if
condition|(
name|addr
operator|==
name|MAP_FAILED
condition|)
block|{
name|ngx_log_error
argument_list|(
name|NGX_LOG_ERR
argument_list|,
name|log
argument_list|,
name|ngx_errno
argument_list|,
literal|"ngx_create_os_thread_stacks: mmap failed"
argument_list|)
expr_stmt|;
return|return
operator|-
literal|1
return|;
block|}
name|nxg_stacks_start
operator|=
name|addr
expr_stmt|;
name|nxg_stacks_end
operator|=
name|addr
operator|+
name|n
operator|*
name|size
expr_stmt|;
name|nxg_stack_size
operator|=
name|size
expr_stmt|;
comment|/* create thread errno array */
name|ngx_test_null
argument_list|(
name|errnos
argument_list|,
name|ngx_calloc
argument_list|(
name|n
operator|*
sizeof|sizeof
argument_list|(
name|int
argument_list|)
argument_list|)
argument_list|,
operator|-
literal|1
argument_list|)
expr_stmt|;
comment|/* create thread tid array */
name|ngx_test_null
argument_list|(
name|ngx_os_tids
argument_list|,
name|ngx_calloc
argument_list|(
name|n
operator|*
sizeof|sizeof
argument_list|(
name|ngx_os_tid_t
argument_list|)
argument_list|)
argument_list|,
operator|-
literal|1
argument_list|)
expr_stmt|;
comment|/* allow spinlock in malloc() */
name|__isthreaded
operator|=
literal|1
expr_stmt|;
return|return
literal|0
return|;
block|}
end_function

end_unit

