begin_unit|revision:1.0.0;language:C;cregit-version:0.0.1
begin_comment
comment|/*  * Copyright (C) Igor Sysoev  * Copyright (C) Nginx, Inc.  */
end_comment

begin_include
include|#
directive|include
file|<ngx_config.h>
end_include

begin_include
include|#
directive|include
file|<ngx_core.h>
end_include

begin_include
include|#
directive|include
file|<ngx_event.h>
end_include

begin_comment
comment|/*  * It seems that Darwin 9.4 (Mac OS X 1.5) sendfile() has the same  * old bug as early FreeBSD sendfile() syscall:  * http://bugs.freebsd.org/33771  *  * Besides sendfile() has another bug: if one calls sendfile()  * with both a header and a trailer, then sendfile() ignores a file part  * at all and sends only the header and the trailer together.  * For this reason we send a trailer only if there is no a header.  *  * Although sendfile() allows to pass a header or a trailer,  * it may send the header or the trailer and a part of the file  * in different packets.  And FreeBSD workaround (TCP_NOPUSH option)  * does not help.  */
end_comment

begin_function
name|ngx_chain_t
modifier|*
DECL|function|ngx_darwin_sendfile_chain (ngx_connection_t * c,ngx_chain_t * in,off_t limit)
name|ngx_darwin_sendfile_chain
parameter_list|(
name|ngx_connection_t
modifier|*
name|c
parameter_list|,
name|ngx_chain_t
modifier|*
name|in
parameter_list|,
name|off_t
name|limit
parameter_list|)
block|{
name|int
name|rc
decl_stmt|;
name|off_t
name|send
decl_stmt|,
name|prev_send
decl_stmt|,
name|sent
decl_stmt|;
name|off_t
name|file_size
decl_stmt|;
name|ngx_uint_t
name|eintr
decl_stmt|;
name|ngx_err_t
name|err
decl_stmt|;
name|ngx_buf_t
modifier|*
name|file
decl_stmt|;
name|ngx_event_t
modifier|*
name|wev
decl_stmt|;
name|ngx_chain_t
modifier|*
name|cl
decl_stmt|;
name|ngx_iovec_t
name|header
decl_stmt|,
name|trailer
decl_stmt|;
name|struct
name|sf_hdtr
name|hdtr
decl_stmt|;
name|struct
name|iovec
name|headers
index|[
name|NGX_IOVS_PREALLOCATE
index|]
decl_stmt|;
name|struct
name|iovec
name|trailers
index|[
name|NGX_IOVS_PREALLOCATE
index|]
decl_stmt|;
name|wev
operator|=
name|c
operator|->
name|write
expr_stmt|;
if|if
condition|(
operator|!
name|wev
operator|->
name|ready
condition|)
block|{
return|return
name|in
return|;
block|}
if|#
directive|if
operator|(
name|NGX_HAVE_KQUEUE
operator|)
if|if
condition|(
operator|(
name|ngx_event_flags
operator|&
name|NGX_USE_KQUEUE_EVENT
operator|)
operator|&&
name|wev
operator|->
name|pending_eof
condition|)
block|{
operator|(
name|void
operator|)
name|ngx_connection_error
argument_list|(
name|c
argument_list|,
name|wev
operator|->
name|kq_errno
argument_list|,
literal|"kevent() reported about an closed connection"
argument_list|)
expr_stmt|;
name|wev
operator|->
name|error
operator|=
literal|1
expr_stmt|;
return|return
name|NGX_CHAIN_ERROR
return|;
block|}
endif|#
directive|endif
comment|/* the maximum limit size is the maximum size_t value - the page size */
if|if
condition|(
name|limit
operator|==
literal|0
operator|||
name|limit
operator|>
operator|(
name|off_t
operator|)
operator|(
name|NGX_MAX_SIZE_T_VALUE
operator|-
name|ngx_pagesize
operator|)
condition|)
block|{
name|limit
operator|=
name|NGX_MAX_SIZE_T_VALUE
operator|-
name|ngx_pagesize
expr_stmt|;
block|}
name|send
operator|=
literal|0
expr_stmt|;
name|header
operator|.
name|iovs
operator|=
name|headers
expr_stmt|;
name|header
operator|.
name|nalloc
operator|=
name|NGX_IOVS_PREALLOCATE
expr_stmt|;
name|trailer
operator|.
name|iovs
operator|=
name|trailers
expr_stmt|;
name|trailer
operator|.
name|nalloc
operator|=
name|NGX_IOVS_PREALLOCATE
expr_stmt|;
for|for
control|(
init|;
condition|;
control|)
block|{
name|eintr
operator|=
literal|0
expr_stmt|;
name|prev_send
operator|=
name|send
expr_stmt|;
comment|/* create the header iovec and coalesce the neighbouring bufs */
name|cl
operator|=
name|ngx_output_chain_to_iovec
argument_list|(
operator|&
name|header
argument_list|,
name|in
argument_list|,
name|limit
operator|-
name|send
argument_list|,
name|c
operator|->
name|log
argument_list|)
expr_stmt|;
if|if
condition|(
name|cl
operator|==
name|NGX_CHAIN_ERROR
condition|)
block|{
return|return
name|NGX_CHAIN_ERROR
return|;
block|}
name|send
operator|+=
name|header
operator|.
name|size
expr_stmt|;
if|if
condition|(
name|cl
operator|&&
name|cl
operator|->
name|buf
operator|->
name|in_file
operator|&&
name|send
operator|<
name|limit
condition|)
block|{
name|file
operator|=
name|cl
operator|->
name|buf
expr_stmt|;
comment|/* coalesce the neighbouring file bufs */
name|file_size
operator|=
name|ngx_chain_coalesce_file
argument_list|(
operator|&
name|cl
argument_list|,
name|limit
operator|-
name|send
argument_list|)
expr_stmt|;
name|send
operator|+=
name|file_size
expr_stmt|;
if|if
condition|(
name|header
operator|.
name|count
operator|==
literal|0
condition|)
block|{
comment|/*                  * create the trailer iovec and coalesce the neighbouring bufs                  */
name|cl
operator|=
name|ngx_output_chain_to_iovec
argument_list|(
operator|&
name|trailer
argument_list|,
name|cl
argument_list|,
name|limit
operator|-
name|send
argument_list|,
name|c
operator|->
name|log
argument_list|)
expr_stmt|;
if|if
condition|(
name|cl
operator|==
name|NGX_CHAIN_ERROR
condition|)
block|{
return|return
name|NGX_CHAIN_ERROR
return|;
block|}
name|send
operator|+=
name|trailer
operator|.
name|size
expr_stmt|;
block|}
comment|/*              * sendfile() returns EINVAL if sf_hdtr's count is 0,              * but corresponding pointer is not NULL              */
name|hdtr
operator|.
name|headers
operator|=
name|header
operator|.
name|count
condition|?
name|header
operator|.
name|iovs
else|:
name|NULL
expr_stmt|;
name|hdtr
operator|.
name|hdr_cnt
operator|=
name|header
operator|.
name|count
expr_stmt|;
name|hdtr
operator|.
name|trailers
operator|=
name|trailer
operator|.
name|count
condition|?
name|trailer
operator|.
name|iovs
else|:
name|NULL
expr_stmt|;
name|hdtr
operator|.
name|trl_cnt
operator|=
name|trailer
operator|.
name|count
expr_stmt|;
name|sent
operator|=
name|header
operator|.
name|size
operator|+
name|file_size
expr_stmt|;
name|ngx_log_debug3
argument_list|(
name|NGX_LOG_DEBUG_EVENT
argument_list|,
name|c
operator|->
name|log
argument_list|,
literal|0
argument_list|,
literal|"sendfile: @%O %O h:%uz"
argument_list|,
name|file
operator|->
name|file_pos
argument_list|,
name|sent
argument_list|,
name|header
operator|.
name|size
argument_list|)
expr_stmt|;
name|rc
operator|=
name|sendfile
argument_list|(
name|file
operator|->
name|file
operator|->
name|fd
argument_list|,
name|c
operator|->
name|fd
argument_list|,
name|file
operator|->
name|file_pos
argument_list|,
operator|&
name|sent
argument_list|,
operator|&
name|hdtr
argument_list|,
literal|0
argument_list|)
expr_stmt|;
if|if
condition|(
name|rc
operator|==
operator|-
literal|1
condition|)
block|{
name|err
operator|=
name|ngx_errno
expr_stmt|;
switch|switch
condition|(
name|err
condition|)
block|{
case|case
name|NGX_EAGAIN
case|:
break|break;
case|case
name|NGX_EINTR
case|:
name|eintr
operator|=
literal|1
expr_stmt|;
break|break;
default|default:
name|wev
operator|->
name|error
operator|=
literal|1
expr_stmt|;
operator|(
name|void
operator|)
name|ngx_connection_error
argument_list|(
name|c
argument_list|,
name|err
argument_list|,
literal|"sendfile() failed"
argument_list|)
expr_stmt|;
return|return
name|NGX_CHAIN_ERROR
return|;
block|}
name|ngx_log_debug1
argument_list|(
name|NGX_LOG_DEBUG_EVENT
argument_list|,
name|c
operator|->
name|log
argument_list|,
name|err
argument_list|,
literal|"sendfile() sent only %O bytes"
argument_list|,
name|sent
argument_list|)
expr_stmt|;
block|}
if|if
condition|(
name|rc
operator|==
literal|0
operator|&&
name|sent
operator|==
literal|0
condition|)
block|{
comment|/*                  * if rc and sent equal to zero, then someone                  * has truncated the file, so the offset became beyond                  * the end of the file                  */
name|ngx_log_error
argument_list|(
name|NGX_LOG_ALERT
argument_list|,
name|c
operator|->
name|log
argument_list|,
literal|0
argument_list|,
literal|"sendfile() reported that \"%s\" was truncated"
argument_list|,
name|file
operator|->
name|file
operator|->
name|name
operator|.
name|data
argument_list|)
expr_stmt|;
return|return
name|NGX_CHAIN_ERROR
return|;
block|}
name|ngx_log_debug4
argument_list|(
name|NGX_LOG_DEBUG_EVENT
argument_list|,
name|c
operator|->
name|log
argument_list|,
literal|0
argument_list|,
literal|"sendfile: %d, @%O %O:%O"
argument_list|,
name|rc
argument_list|,
name|file
operator|->
name|file_pos
argument_list|,
name|sent
argument_list|,
name|file_size
operator|+
name|header
operator|.
name|size
argument_list|)
expr_stmt|;
block|}
else|else
block|{
name|rc
operator|=
name|writev
argument_list|(
name|c
operator|->
name|fd
argument_list|,
name|header
operator|.
name|iovs
argument_list|,
name|header
operator|.
name|count
argument_list|)
expr_stmt|;
name|ngx_log_debug2
argument_list|(
name|NGX_LOG_DEBUG_EVENT
argument_list|,
name|c
operator|->
name|log
argument_list|,
literal|0
argument_list|,
literal|"writev: %d of %uz"
argument_list|,
name|rc
argument_list|,
name|header
operator|.
name|size
argument_list|)
expr_stmt|;
if|if
condition|(
name|rc
operator|==
operator|-
literal|1
condition|)
block|{
name|err
operator|=
name|ngx_errno
expr_stmt|;
switch|switch
condition|(
name|err
condition|)
block|{
case|case
name|NGX_EAGAIN
case|:
break|break;
case|case
name|NGX_EINTR
case|:
name|eintr
operator|=
literal|1
expr_stmt|;
break|break;
default|default:
name|wev
operator|->
name|error
operator|=
literal|1
expr_stmt|;
name|ngx_connection_error
argument_list|(
name|c
argument_list|,
name|err
argument_list|,
literal|"writev() failed"
argument_list|)
expr_stmt|;
return|return
name|NGX_CHAIN_ERROR
return|;
block|}
name|ngx_log_debug0
argument_list|(
name|NGX_LOG_DEBUG_EVENT
argument_list|,
name|c
operator|->
name|log
argument_list|,
name|err
argument_list|,
literal|"writev() not ready"
argument_list|)
expr_stmt|;
block|}
name|sent
operator|=
name|rc
operator|>
literal|0
condition|?
name|rc
else|:
literal|0
expr_stmt|;
block|}
name|c
operator|->
name|sent
operator|+=
name|sent
expr_stmt|;
name|in
operator|=
name|ngx_chain_update_sent
argument_list|(
name|in
argument_list|,
name|sent
argument_list|)
expr_stmt|;
if|if
condition|(
name|eintr
condition|)
block|{
name|send
operator|=
name|prev_send
operator|+
name|sent
expr_stmt|;
continue|continue;
block|}
if|if
condition|(
name|send
operator|-
name|prev_send
operator|!=
name|sent
condition|)
block|{
name|wev
operator|->
name|ready
operator|=
literal|0
expr_stmt|;
return|return
name|in
return|;
block|}
if|if
condition|(
name|send
operator|>=
name|limit
operator|||
name|in
operator|==
name|NULL
condition|)
block|{
return|return
name|in
return|;
block|}
block|}
block|}
end_function

end_unit

