begin_unit|revision:1.0.0;language:C;cregit-version:0.0.1
begin_ifndef
ifndef|#
directive|ifndef
name|_NGX_HTTP_CONFIG_COMMAND_H_INCLUDED_
end_ifndef

begin_define
DECL|macro|_NGX_HTTP_CONFIG_COMMAND_H_INCLUDED_
define|#
directive|define
name|_NGX_HTTP_CONFIG_COMMAND_H_INCLUDED_
end_define

begin_define
DECL|macro|NGX_CONF_TAKE1
define|#
directive|define
name|NGX_CONF_TAKE1
value|0
end_define

begin_define
DECL|macro|NGX_CONF_ITERATE
define|#
directive|define
name|NGX_CONF_ITERATE
value|0
end_define

begin_define
DECL|macro|NGX_CONF_UNSET
define|#
directive|define
name|NGX_CONF_UNSET
value|-1
end_define

begin_typedef
DECL|struct|__anon29fb8ac50108
typedef|typedef
struct|struct
block|{
DECL|member|name
name|char
modifier|*
name|name
decl_stmt|;
DECL|member|set
name|char
modifier|*
function_decl|(
modifier|*
name|set
function_decl|)
parameter_list|()
function_decl|;
DECL|member|offset
name|int
name|offset
decl_stmt|;
DECL|member|zone
name|int
name|zone
decl_stmt|;
DECL|member|type
name|int
name|type
decl_stmt|;
DECL|member|description
name|char
modifier|*
name|description
decl_stmt|;
DECL|typedef|ngx_command_t
block|}
name|ngx_command_t
typedef|;
end_typedef

begin_function_decl
name|char
modifier|*
name|ngx_conf_set_size_slot
parameter_list|(
name|char
modifier|*
name|conf
parameter_list|,
name|int
name|offset
parameter_list|,
name|char
modifier|*
name|value
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|char
modifier|*
name|ngx_conf_set_time_slot
parameter_list|(
name|char
modifier|*
name|conf
parameter_list|,
name|int
name|offset
parameter_list|,
name|char
modifier|*
name|value
parameter_list|)
function_decl|;
end_function_decl

begin_endif
endif|#
directive|endif
endif|_NGX_HTTP_CONFIG_COMMAND_H_INCLUDED_
end_endif

end_unit

