begin_unit|revision:1.0.0;language:C;cregit-version:0.0.1
begin_comment
comment|/*  * Copyright (C) Igor Sysoev  * Copyright (C) Maxim Dounin  * Copyright (C) Nginx, Inc.  */
end_comment

begin_ifndef
ifndef|#
directive|ifndef
name|_NGX_MODULE_H_INCLUDED_
end_ifndef

begin_define
DECL|macro|_NGX_MODULE_H_INCLUDED_
define|#
directive|define
name|_NGX_MODULE_H_INCLUDED_
end_define

begin_include
include|#
directive|include
file|<ngx_config.h>
end_include

begin_include
include|#
directive|include
file|<ngx_core.h>
end_include

begin_define
DECL|macro|NGX_MODULE_V1
define|#
directive|define
name|NGX_MODULE_V1
value|0, 0, 0, 0, 0, 0, 1
end_define

begin_define
DECL|macro|NGX_MODULE_V1_PADDING
define|#
directive|define
name|NGX_MODULE_V1_PADDING
value|0, 0, 0, 0, 0, 0, 0, 0
end_define

begin_struct
DECL|struct|ngx_module_s
struct|struct
name|ngx_module_s
block|{
DECL|member|ctx_index
name|ngx_uint_t
name|ctx_index
decl_stmt|;
DECL|member|index
name|ngx_uint_t
name|index
decl_stmt|;
DECL|member|spare0
name|ngx_uint_t
name|spare0
decl_stmt|;
DECL|member|spare1
name|ngx_uint_t
name|spare1
decl_stmt|;
DECL|member|spare2
name|ngx_uint_t
name|spare2
decl_stmt|;
DECL|member|spare3
name|ngx_uint_t
name|spare3
decl_stmt|;
DECL|member|version
name|ngx_uint_t
name|version
decl_stmt|;
DECL|member|ctx
name|void
modifier|*
name|ctx
decl_stmt|;
DECL|member|commands
name|ngx_command_t
modifier|*
name|commands
decl_stmt|;
DECL|member|type
name|ngx_uint_t
name|type
decl_stmt|;
DECL|member|init_master
name|ngx_int_t
function_decl|(
modifier|*
name|init_master
function_decl|)
parameter_list|(
name|ngx_log_t
modifier|*
name|log
parameter_list|)
function_decl|;
DECL|member|init_module
name|ngx_int_t
function_decl|(
modifier|*
name|init_module
function_decl|)
parameter_list|(
name|ngx_cycle_t
modifier|*
name|cycle
parameter_list|)
function_decl|;
DECL|member|init_process
name|ngx_int_t
function_decl|(
modifier|*
name|init_process
function_decl|)
parameter_list|(
name|ngx_cycle_t
modifier|*
name|cycle
parameter_list|)
function_decl|;
DECL|member|init_thread
name|ngx_int_t
function_decl|(
modifier|*
name|init_thread
function_decl|)
parameter_list|(
name|ngx_cycle_t
modifier|*
name|cycle
parameter_list|)
function_decl|;
DECL|member|exit_thread
name|void
function_decl|(
modifier|*
name|exit_thread
function_decl|)
parameter_list|(
name|ngx_cycle_t
modifier|*
name|cycle
parameter_list|)
function_decl|;
DECL|member|exit_process
name|void
function_decl|(
modifier|*
name|exit_process
function_decl|)
parameter_list|(
name|ngx_cycle_t
modifier|*
name|cycle
parameter_list|)
function_decl|;
DECL|member|exit_master
name|void
function_decl|(
modifier|*
name|exit_master
function_decl|)
parameter_list|(
name|ngx_cycle_t
modifier|*
name|cycle
parameter_list|)
function_decl|;
DECL|member|spare_hook0
name|uintptr_t
name|spare_hook0
decl_stmt|;
DECL|member|spare_hook1
name|uintptr_t
name|spare_hook1
decl_stmt|;
DECL|member|spare_hook2
name|uintptr_t
name|spare_hook2
decl_stmt|;
DECL|member|spare_hook3
name|uintptr_t
name|spare_hook3
decl_stmt|;
DECL|member|spare_hook4
name|uintptr_t
name|spare_hook4
decl_stmt|;
DECL|member|spare_hook5
name|uintptr_t
name|spare_hook5
decl_stmt|;
DECL|member|spare_hook6
name|uintptr_t
name|spare_hook6
decl_stmt|;
DECL|member|spare_hook7
name|uintptr_t
name|spare_hook7
decl_stmt|;
block|}
struct|;
end_struct

begin_typedef
DECL|struct|__anon29d9ec3a0108
typedef|typedef
struct|struct
block|{
DECL|member|name
name|ngx_str_t
name|name
decl_stmt|;
DECL|member|create_conf
name|void
modifier|*
function_decl|(
modifier|*
name|create_conf
function_decl|)
parameter_list|(
name|ngx_cycle_t
modifier|*
name|cycle
parameter_list|)
function_decl|;
DECL|member|init_conf
name|char
modifier|*
function_decl|(
modifier|*
name|init_conf
function_decl|)
parameter_list|(
name|ngx_cycle_t
modifier|*
name|cycle
parameter_list|,
name|void
modifier|*
name|conf
parameter_list|)
function_decl|;
DECL|typedef|ngx_core_module_t
block|}
name|ngx_core_module_t
typedef|;
end_typedef

begin_function_decl
name|ngx_int_t
name|ngx_preinit_modules
parameter_list|()
function_decl|;
end_function_decl

begin_function_decl
name|ngx_int_t
name|ngx_init_modules
parameter_list|(
name|ngx_cycle_t
modifier|*
name|cycle
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|ngx_int_t
name|ngx_count_modules
parameter_list|(
name|ngx_cycle_t
modifier|*
name|cycle
parameter_list|,
name|ngx_uint_t
name|type
parameter_list|)
function_decl|;
end_function_decl

begin_decl_stmt
specifier|extern
name|ngx_module_t
modifier|*
name|ngx_modules
index|[]
decl_stmt|;
end_decl_stmt

begin_decl_stmt
specifier|extern
name|ngx_uint_t
name|ngx_max_module
decl_stmt|;
end_decl_stmt

begin_endif
endif|#
directive|endif
end_endif

begin_comment
comment|/* _NGX_MODULE_H_INCLUDED_ */
end_comment

end_unit

