begin_unit|revision:1.0.0;language:C;cregit-version:0.0.1
begin_comment
comment|/*  * Copyright (C) Roman Arutyunyan  * Copyright (C) Nginx, Inc.  */
end_comment

begin_include
include|#
directive|include
file|<ngx_config.h>
end_include

begin_include
include|#
directive|include
file|<ngx_core.h>
end_include

begin_include
include|#
directive|include
file|<ngx_stream.h>
end_include

begin_typedef
DECL|struct|__anon2a3efb520108
typedef|typedef
struct|struct
block|{
DECL|member|text
name|ngx_stream_complex_value_t
name|text
decl_stmt|;
DECL|typedef|ngx_stream_return_srv_conf_t
block|}
name|ngx_stream_return_srv_conf_t
typedef|;
end_typedef

begin_typedef
DECL|struct|__anon2a3efb520208
typedef|typedef
struct|struct
block|{
DECL|member|buf
name|ngx_buf_t
name|buf
decl_stmt|;
DECL|typedef|ngx_stream_return_ctx_t
block|}
name|ngx_stream_return_ctx_t
typedef|;
end_typedef

begin_function_decl
specifier|static
name|void
name|ngx_stream_return_handler
parameter_list|(
name|ngx_stream_session_t
modifier|*
name|s
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
name|ngx_stream_return_write_handler
parameter_list|(
name|ngx_event_t
modifier|*
name|ev
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|void
modifier|*
name|ngx_stream_return_create_srv_conf
parameter_list|(
name|ngx_conf_t
modifier|*
name|cf
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
specifier|static
name|char
modifier|*
name|ngx_stream_return
parameter_list|(
name|ngx_conf_t
modifier|*
name|cf
parameter_list|,
name|ngx_command_t
modifier|*
name|cmd
parameter_list|,
name|void
modifier|*
name|conf
parameter_list|)
function_decl|;
end_function_decl

begin_decl_stmt
DECL|variable|ngx_stream_return_commands
specifier|static
name|ngx_command_t
name|ngx_stream_return_commands
index|[]
init|=
block|{
block|{
name|ngx_string
argument_list|(
literal|"return"
argument_list|)
block|,
name|NGX_STREAM_SRV_CONF
operator||
name|NGX_CONF_TAKE1
block|,
name|ngx_stream_return
block|,
name|NGX_STREAM_SRV_CONF_OFFSET
block|,
literal|0
block|,
name|NULL
block|}
block|,
name|ngx_null_command
block|}
decl_stmt|;
end_decl_stmt

begin_decl_stmt
DECL|variable|ngx_stream_return_module_ctx
specifier|static
name|ngx_stream_module_t
name|ngx_stream_return_module_ctx
init|=
block|{
name|NULL
block|,
comment|/* preconfiguration */
name|NULL
block|,
comment|/* postconfiguration */
name|NULL
block|,
comment|/* create main configuration */
name|NULL
block|,
comment|/* init main configuration */
name|ngx_stream_return_create_srv_conf
block|,
comment|/* create server configuration */
name|NULL
block|,
comment|/* merge server configuration */
block|}
decl_stmt|;
end_decl_stmt

begin_decl_stmt
DECL|variable|ngx_stream_return_module
name|ngx_module_t
name|ngx_stream_return_module
init|=
block|{
name|NGX_MODULE_V1
block|,
operator|&
name|ngx_stream_return_module_ctx
block|,
comment|/* module context */
name|ngx_stream_return_commands
block|,
comment|/* module directives */
name|NGX_STREAM_MODULE
block|,
comment|/* module type */
name|NULL
block|,
comment|/* init master */
name|NULL
block|,
comment|/* init module */
name|NULL
block|,
comment|/* init process */
name|NULL
block|,
comment|/* init thread */
name|NULL
block|,
comment|/* exit thread */
name|NULL
block|,
comment|/* exit process */
name|NULL
block|,
comment|/* exit master */
name|NGX_MODULE_V1_PADDING
block|}
decl_stmt|;
end_decl_stmt

begin_function
specifier|static
name|void
DECL|function|ngx_stream_return_handler (ngx_stream_session_t * s)
name|ngx_stream_return_handler
parameter_list|(
name|ngx_stream_session_t
modifier|*
name|s
parameter_list|)
block|{
name|ngx_str_t
name|text
decl_stmt|;
name|ngx_connection_t
modifier|*
name|c
decl_stmt|;
name|ngx_stream_return_ctx_t
modifier|*
name|ctx
decl_stmt|;
name|ngx_stream_return_srv_conf_t
modifier|*
name|rscf
decl_stmt|;
name|c
operator|=
name|s
operator|->
name|connection
expr_stmt|;
name|c
operator|->
name|log
operator|->
name|action
operator|=
literal|"returning text"
expr_stmt|;
name|rscf
operator|=
name|ngx_stream_get_module_srv_conf
argument_list|(
name|s
argument_list|,
name|ngx_stream_return_module
argument_list|)
expr_stmt|;
if|if
condition|(
name|ngx_stream_complex_value
argument_list|(
name|s
argument_list|,
operator|&
name|rscf
operator|->
name|text
argument_list|,
operator|&
name|text
argument_list|)
operator|!=
name|NGX_OK
condition|)
block|{
name|ngx_stream_close_connection
argument_list|(
name|c
argument_list|)
expr_stmt|;
return|return;
block|}
name|ngx_log_debug1
argument_list|(
name|NGX_LOG_DEBUG_STREAM
argument_list|,
name|c
operator|->
name|log
argument_list|,
literal|0
argument_list|,
literal|"stream return text: \"%V\""
argument_list|,
operator|&
name|text
argument_list|)
expr_stmt|;
if|if
condition|(
name|text
operator|.
name|len
operator|==
literal|0
condition|)
block|{
name|ngx_stream_close_connection
argument_list|(
name|c
argument_list|)
expr_stmt|;
return|return;
block|}
name|ctx
operator|=
name|ngx_pcalloc
argument_list|(
name|c
operator|->
name|pool
argument_list|,
sizeof|sizeof
argument_list|(
name|ngx_stream_return_ctx_t
argument_list|)
argument_list|)
expr_stmt|;
if|if
condition|(
name|ctx
operator|==
name|NULL
condition|)
block|{
name|ngx_stream_close_connection
argument_list|(
name|c
argument_list|)
expr_stmt|;
return|return;
block|}
name|ngx_stream_set_ctx
argument_list|(
name|s
argument_list|,
name|ctx
argument_list|,
name|ngx_stream_return_module
argument_list|)
expr_stmt|;
name|ctx
operator|->
name|buf
operator|.
name|pos
operator|=
name|text
operator|.
name|data
expr_stmt|;
name|ctx
operator|->
name|buf
operator|.
name|last
operator|=
name|text
operator|.
name|data
operator|+
name|text
operator|.
name|len
expr_stmt|;
name|c
operator|->
name|write
operator|->
name|handler
operator|=
name|ngx_stream_return_write_handler
expr_stmt|;
name|ngx_stream_return_write_handler
argument_list|(
name|c
operator|->
name|write
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
specifier|static
name|void
DECL|function|ngx_stream_return_write_handler (ngx_event_t * ev)
name|ngx_stream_return_write_handler
parameter_list|(
name|ngx_event_t
modifier|*
name|ev
parameter_list|)
block|{
name|ssize_t
name|n
decl_stmt|;
name|ngx_buf_t
modifier|*
name|b
decl_stmt|;
name|ngx_connection_t
modifier|*
name|c
decl_stmt|;
name|ngx_stream_session_t
modifier|*
name|s
decl_stmt|;
name|ngx_stream_return_ctx_t
modifier|*
name|ctx
decl_stmt|;
name|c
operator|=
name|ev
operator|->
name|data
expr_stmt|;
name|s
operator|=
name|c
operator|->
name|data
expr_stmt|;
if|if
condition|(
name|ev
operator|->
name|timedout
condition|)
block|{
name|ngx_connection_error
argument_list|(
name|c
argument_list|,
name|NGX_ETIMEDOUT
argument_list|,
literal|"connection timed out"
argument_list|)
expr_stmt|;
name|ngx_stream_close_connection
argument_list|(
name|c
argument_list|)
expr_stmt|;
return|return;
block|}
if|if
condition|(
name|ev
operator|->
name|ready
condition|)
block|{
name|ctx
operator|=
name|ngx_stream_get_module_ctx
argument_list|(
name|s
argument_list|,
name|ngx_stream_return_module
argument_list|)
expr_stmt|;
name|b
operator|=
operator|&
name|ctx
operator|->
name|buf
expr_stmt|;
name|n
operator|=
name|c
operator|->
name|send
argument_list|(
name|c
argument_list|,
name|b
operator|->
name|pos
argument_list|,
name|b
operator|->
name|last
operator|-
name|b
operator|->
name|pos
argument_list|)
expr_stmt|;
if|if
condition|(
name|n
operator|==
name|NGX_ERROR
condition|)
block|{
name|ngx_stream_close_connection
argument_list|(
name|c
argument_list|)
expr_stmt|;
return|return;
block|}
if|if
condition|(
name|n
operator|>
literal|0
condition|)
block|{
name|b
operator|->
name|pos
operator|+=
name|n
expr_stmt|;
if|if
condition|(
name|b
operator|->
name|pos
operator|==
name|b
operator|->
name|last
condition|)
block|{
name|ngx_stream_close_connection
argument_list|(
name|c
argument_list|)
expr_stmt|;
return|return;
block|}
block|}
block|}
if|if
condition|(
name|ngx_handle_write_event
argument_list|(
name|ev
argument_list|,
literal|0
argument_list|)
operator|!=
name|NGX_OK
condition|)
block|{
name|ngx_stream_close_connection
argument_list|(
name|c
argument_list|)
expr_stmt|;
return|return;
block|}
name|ngx_add_timer
argument_list|(
name|ev
argument_list|,
literal|5000
argument_list|)
expr_stmt|;
block|}
end_function

begin_function
specifier|static
name|void
modifier|*
DECL|function|ngx_stream_return_create_srv_conf (ngx_conf_t * cf)
name|ngx_stream_return_create_srv_conf
parameter_list|(
name|ngx_conf_t
modifier|*
name|cf
parameter_list|)
block|{
name|ngx_stream_return_srv_conf_t
modifier|*
name|conf
decl_stmt|;
name|conf
operator|=
name|ngx_pcalloc
argument_list|(
name|cf
operator|->
name|pool
argument_list|,
sizeof|sizeof
argument_list|(
name|ngx_stream_return_srv_conf_t
argument_list|)
argument_list|)
expr_stmt|;
if|if
condition|(
name|conf
operator|==
name|NULL
condition|)
block|{
return|return
name|NULL
return|;
block|}
return|return
name|conf
return|;
block|}
end_function

begin_function
specifier|static
name|char
modifier|*
DECL|function|ngx_stream_return (ngx_conf_t * cf,ngx_command_t * cmd,void * conf)
name|ngx_stream_return
parameter_list|(
name|ngx_conf_t
modifier|*
name|cf
parameter_list|,
name|ngx_command_t
modifier|*
name|cmd
parameter_list|,
name|void
modifier|*
name|conf
parameter_list|)
block|{
name|ngx_stream_return_srv_conf_t
modifier|*
name|rscf
init|=
name|conf
decl_stmt|;
name|ngx_str_t
modifier|*
name|value
decl_stmt|;
name|ngx_stream_core_srv_conf_t
modifier|*
name|cscf
decl_stmt|;
name|ngx_stream_compile_complex_value_t
name|ccv
decl_stmt|;
if|if
condition|(
name|rscf
operator|->
name|text
operator|.
name|value
operator|.
name|data
condition|)
block|{
return|return
literal|"is duplicate"
return|;
block|}
name|value
operator|=
name|cf
operator|->
name|args
operator|->
name|elts
expr_stmt|;
name|ngx_memzero
argument_list|(
operator|&
name|ccv
argument_list|,
sizeof|sizeof
argument_list|(
name|ngx_stream_compile_complex_value_t
argument_list|)
argument_list|)
expr_stmt|;
name|ccv
operator|.
name|cf
operator|=
name|cf
expr_stmt|;
name|ccv
operator|.
name|value
operator|=
operator|&
name|value
index|[
literal|1
index|]
expr_stmt|;
name|ccv
operator|.
name|complex_value
operator|=
operator|&
name|rscf
operator|->
name|text
expr_stmt|;
if|if
condition|(
name|ngx_stream_compile_complex_value
argument_list|(
operator|&
name|ccv
argument_list|)
operator|!=
name|NGX_OK
condition|)
block|{
return|return
name|NGX_CONF_ERROR
return|;
block|}
name|cscf
operator|=
name|ngx_stream_conf_get_module_srv_conf
argument_list|(
name|cf
argument_list|,
name|ngx_stream_core_module
argument_list|)
expr_stmt|;
name|cscf
operator|->
name|handler
operator|=
name|ngx_stream_return_handler
expr_stmt|;
return|return
name|NGX_CONF_OK
return|;
block|}
end_function

end_unit

