begin_unit|revision:1.0.0;language:C;cregit-version:0.0.1
begin_comment
comment|/*  * Copyright (C) Igor Sysoev  * Copyright (C) Nginx, Inc.  */
end_comment

begin_ifndef
ifndef|#
directive|ifndef
name|_NGX_STREAM_VARIABLES_H_INCLUDED_
end_ifndef

begin_define
DECL|macro|_NGX_STREAM_VARIABLES_H_INCLUDED_
define|#
directive|define
name|_NGX_STREAM_VARIABLES_H_INCLUDED_
end_define

begin_include
include|#
directive|include
file|<ngx_config.h>
end_include

begin_include
include|#
directive|include
file|<ngx_core.h>
end_include

begin_include
include|#
directive|include
file|<ngx_stream.h>
end_include

begin_typedef
DECL|typedef|ngx_stream_variable_value_t
typedef|typedef
name|ngx_variable_value_t
name|ngx_stream_variable_value_t
typedef|;
end_typedef

begin_define
DECL|macro|ngx_stream_variable (v)
define|#
directive|define
name|ngx_stream_variable
parameter_list|(
name|v
parameter_list|)
value|{ sizeof(v) - 1, 1, 0, 0, 0, (u_char *) v }
end_define

begin_typedef
DECL|typedef|ngx_stream_variable_t
typedef|typedef
name|struct
name|ngx_stream_variable_s
name|ngx_stream_variable_t
typedef|;
end_typedef

begin_typedef
DECL|typedef|ngx_stream_set_variable_pt
typedef|typedef
name|void
function_decl|(
modifier|*
name|ngx_stream_set_variable_pt
function_decl|)
parameter_list|(
name|ngx_stream_session_t
modifier|*
name|s
parameter_list|,
name|ngx_stream_variable_value_t
modifier|*
name|v
parameter_list|,
name|uintptr_t
name|data
parameter_list|)
function_decl|;
end_typedef

begin_typedef
DECL|typedef|ngx_stream_get_variable_pt
typedef|typedef
name|ngx_int_t
function_decl|(
modifier|*
name|ngx_stream_get_variable_pt
function_decl|)
parameter_list|(
name|ngx_stream_session_t
modifier|*
name|s
parameter_list|,
name|ngx_stream_variable_value_t
modifier|*
name|v
parameter_list|,
name|uintptr_t
name|data
parameter_list|)
function_decl|;
end_typedef

begin_define
DECL|macro|NGX_STREAM_VAR_CHANGEABLE
define|#
directive|define
name|NGX_STREAM_VAR_CHANGEABLE
value|1
end_define

begin_define
DECL|macro|NGX_STREAM_VAR_NOCACHEABLE
define|#
directive|define
name|NGX_STREAM_VAR_NOCACHEABLE
value|2
end_define

begin_define
DECL|macro|NGX_STREAM_VAR_INDEXED
define|#
directive|define
name|NGX_STREAM_VAR_INDEXED
value|4
end_define

begin_define
DECL|macro|NGX_STREAM_VAR_NOHASH
define|#
directive|define
name|NGX_STREAM_VAR_NOHASH
value|8
end_define

begin_define
DECL|macro|NGX_STREAM_VAR_WEAK
define|#
directive|define
name|NGX_STREAM_VAR_WEAK
value|16
end_define

begin_define
DECL|macro|NGX_STREAM_VAR_PREFIX
define|#
directive|define
name|NGX_STREAM_VAR_PREFIX
value|32
end_define

begin_struct
DECL|struct|ngx_stream_variable_s
struct|struct
name|ngx_stream_variable_s
block|{
DECL|member|name
name|ngx_str_t
name|name
decl_stmt|;
comment|/* must be first to build the hash */
DECL|member|set_handler
name|ngx_stream_set_variable_pt
name|set_handler
decl_stmt|;
DECL|member|get_handler
name|ngx_stream_get_variable_pt
name|get_handler
decl_stmt|;
DECL|member|data
name|uintptr_t
name|data
decl_stmt|;
DECL|member|flags
name|ngx_uint_t
name|flags
decl_stmt|;
DECL|member|index
name|ngx_uint_t
name|index
decl_stmt|;
block|}
struct|;
end_struct

begin_define
DECL|macro|ngx_stream_null_variable
define|#
directive|define
name|ngx_stream_null_variable
value|{ ngx_null_string, NULL, NULL, 0, 0, 0 }
end_define

begin_function_decl
name|ngx_stream_variable_t
modifier|*
name|ngx_stream_add_variable
parameter_list|(
name|ngx_conf_t
modifier|*
name|cf
parameter_list|,
name|ngx_str_t
modifier|*
name|name
parameter_list|,
name|ngx_uint_t
name|flags
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|ngx_int_t
name|ngx_stream_get_variable_index
parameter_list|(
name|ngx_conf_t
modifier|*
name|cf
parameter_list|,
name|ngx_str_t
modifier|*
name|name
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|ngx_stream_variable_value_t
modifier|*
name|ngx_stream_get_indexed_variable
parameter_list|(
name|ngx_stream_session_t
modifier|*
name|s
parameter_list|,
name|ngx_uint_t
name|index
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|ngx_stream_variable_value_t
modifier|*
name|ngx_stream_get_flushed_variable
parameter_list|(
name|ngx_stream_session_t
modifier|*
name|s
parameter_list|,
name|ngx_uint_t
name|index
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|ngx_stream_variable_value_t
modifier|*
name|ngx_stream_get_variable
parameter_list|(
name|ngx_stream_session_t
modifier|*
name|s
parameter_list|,
name|ngx_str_t
modifier|*
name|name
parameter_list|,
name|ngx_uint_t
name|key
parameter_list|)
function_decl|;
end_function_decl

begin_if
if|#
directive|if
operator|(
name|NGX_PCRE
operator|)
end_if

begin_typedef
DECL|struct|__anon27de3e540108
typedef|typedef
struct|struct
block|{
DECL|member|capture
name|ngx_uint_t
name|capture
decl_stmt|;
DECL|member|index
name|ngx_int_t
name|index
decl_stmt|;
DECL|typedef|ngx_stream_regex_variable_t
block|}
name|ngx_stream_regex_variable_t
typedef|;
end_typedef

begin_typedef
DECL|struct|__anon27de3e540208
typedef|typedef
struct|struct
block|{
DECL|member|regex
name|ngx_regex_t
modifier|*
name|regex
decl_stmt|;
DECL|member|ncaptures
name|ngx_uint_t
name|ncaptures
decl_stmt|;
DECL|member|variables
name|ngx_stream_regex_variable_t
modifier|*
name|variables
decl_stmt|;
DECL|member|nvariables
name|ngx_uint_t
name|nvariables
decl_stmt|;
DECL|member|name
name|ngx_str_t
name|name
decl_stmt|;
DECL|typedef|ngx_stream_regex_t
block|}
name|ngx_stream_regex_t
typedef|;
end_typedef

begin_typedef
DECL|struct|__anon27de3e540308
typedef|typedef
struct|struct
block|{
DECL|member|regex
name|ngx_stream_regex_t
modifier|*
name|regex
decl_stmt|;
DECL|member|value
name|void
modifier|*
name|value
decl_stmt|;
DECL|typedef|ngx_stream_map_regex_t
block|}
name|ngx_stream_map_regex_t
typedef|;
end_typedef

begin_function_decl
name|ngx_stream_regex_t
modifier|*
name|ngx_stream_regex_compile
parameter_list|(
name|ngx_conf_t
modifier|*
name|cf
parameter_list|,
name|ngx_regex_compile_t
modifier|*
name|rc
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|ngx_int_t
name|ngx_stream_regex_exec
parameter_list|(
name|ngx_stream_session_t
modifier|*
name|s
parameter_list|,
name|ngx_stream_regex_t
modifier|*
name|re
parameter_list|,
name|ngx_str_t
modifier|*
name|str
parameter_list|)
function_decl|;
end_function_decl

begin_endif
endif|#
directive|endif
end_endif

begin_typedef
DECL|struct|__anon27de3e540408
typedef|typedef
struct|struct
block|{
DECL|member|hash
name|ngx_hash_combined_t
name|hash
decl_stmt|;
if|#
directive|if
operator|(
name|NGX_PCRE
operator|)
DECL|member|regex
name|ngx_stream_map_regex_t
modifier|*
name|regex
decl_stmt|;
DECL|member|nregex
name|ngx_uint_t
name|nregex
decl_stmt|;
endif|#
directive|endif
DECL|typedef|ngx_stream_map_t
block|}
name|ngx_stream_map_t
typedef|;
end_typedef

begin_function_decl
name|void
modifier|*
name|ngx_stream_map_find
parameter_list|(
name|ngx_stream_session_t
modifier|*
name|s
parameter_list|,
name|ngx_stream_map_t
modifier|*
name|map
parameter_list|,
name|ngx_str_t
modifier|*
name|match
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|ngx_int_t
name|ngx_stream_variables_add_core_vars
parameter_list|(
name|ngx_conf_t
modifier|*
name|cf
parameter_list|)
function_decl|;
end_function_decl

begin_function_decl
name|ngx_int_t
name|ngx_stream_variables_init_vars
parameter_list|(
name|ngx_conf_t
modifier|*
name|cf
parameter_list|)
function_decl|;
end_function_decl

begin_decl_stmt
specifier|extern
name|ngx_stream_variable_value_t
name|ngx_stream_variable_null_value
decl_stmt|;
end_decl_stmt

begin_decl_stmt
specifier|extern
name|ngx_stream_variable_value_t
name|ngx_stream_variable_true_value
decl_stmt|;
end_decl_stmt

begin_endif
endif|#
directive|endif
end_endif

begin_comment
comment|/* _NGX_STREAM_VARIABLES_H_INCLUDED_ */
end_comment

end_unit

